import { RECEIPT_AND_COLLECTION_ROUTES } from "./rc_routes";
import { RECEIPT_AND_COLLECTION_ELEMENTS } from "./rc_elements";

export const receipt_and_collection = [
  // Receipt
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_RECEIPT_PAGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_RECEIPT_PAGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_RECEIPT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_RECEIPT,
  },

  // Receipt Reconciliation

  // Synchronize Receipt
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_SYNCHRONIZE_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_SYNCHRONIZE_RECEIPT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_SYNCHRONIZE_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_SYNCHRONIZE_RECEIPT,
  },

  // Reconcile Receipt Histories
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_RECONCILE_RECEIPT_HISTORIES,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_RECONCILE_RECEIPT_HISTORIES,
  },

  // Maintain Electronic Bank Statement
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
    element:
      RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
    element:
      RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPLOAD_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
    element:
      RECEIPT_AND_COLLECTION_ELEMENTS.UPLOAD_MAINTAIN_ELECTRONIC_BANK_STATEMENT,
  },

  // Bank
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_MASTER_BANK,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_MASTER_BANK,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_MASTER_BANK,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_MASTER_BANK,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_MASTER_BANK,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_MASTER_BANK,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_MASTER_BANK,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_MASTER_BANK,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_ACCOUNT_INFORMATION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_ACCOUNT_INFORMATION,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_ACCOUNT_INFORMATION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_ACCOUNT_INFORMATTION,
  },
  //  {
  //     path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_MASTER_BANK,
  //   element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_MASTER_BANK,
  // },

  // receipt Histories
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_RECEIPT_HISTORIES,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_RECEIPT_HISTORIES,
  },

  // payment item
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PAYMENT_ITEM,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PAYMENT_ITEM,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_PAYMENT_ITEM,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_PAYMENT_ITEM,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_PAYMENT_ITEM,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_PAYMENT_ITEM,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_PAYMENT_ITEM,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_PAYMENT_ITEM,
  },
  // payment cycle
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_TRANSACTION_CALENDER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_TRANSACTION_CALENDER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_TRANSACTION_CALENDER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_TRANSACTION_CALENDER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_TRANSACTION_CALENDER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_TRANSACTION_CALENDER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_TRANSACTION_CALENDER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_TRANSACTION_CALENDER,
  },

  //late charge

  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_LATE_CHARGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_LATE_CHARGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_LATE_CHARGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.RECALCULATE_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.RECALCULATE_LATE_CHARGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.REPLACE_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.REPLACE_LATE_CHARGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.REVERSE_LATE_CHARGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.REVERSE_LATE_CHARGE,
  },

  // bridge
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_BRIDGE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_BRIDGE,
  },

  // invoice
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_INVOICE,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_INVOICE,
  },

  // transaction log
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_TRANSACTION_LOG,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_TRANSACTION_LOG,
  },

  //partner
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_PARTNER,
  },

  // payment
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PAYMENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PAYMENT,
  },

  //partner ca
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PARTNER_CA,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PARTNER_CA,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_PARTNER_CA,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_PARTNER_CA,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_PARTNER_CA,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_PARTNER_CA,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_PARTNER_CA,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_PARTNER_CA,
  },

  // ca payment channel
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_CA_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_CA_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_CA_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_CA_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_CA_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_CA_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_CA_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_CA_PAYMENT_CHANNEL,
  },

  //settings
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_SETTINGS,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_SETTINGS,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_SETTINGS,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_SETTINGS,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_SETTINGS,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_SETTINGS,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_SETTINGS,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_SETTINGS,
  },

  // Collecting Agent
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_COLLECTING_AGENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_COLLECTING_AGENT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_COLLECTING_AGENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_COLLECTING_AGENT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_COLLECTING_AGENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_COLLECTING_AGENT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_COLLECTING_AGENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_COLLECTING_AGENT,
  },

  // Payment Channel
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_PAYMENT_CHANNEL,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_PAYMENT_CHANNEL,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_PAYMENT_CHANNEL,
  },

  // Accounting
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_ACCOUNTING,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_ACCOUNTING,
  },

  // Deduction
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_DEDUCTION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_DEDUCTION,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_DEDUCTION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_DEDUCTION,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_DEDUCTION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_DEDUCTION,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_DEDUCTION,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_DEDUCTION,
  },

  // Transfer to Receipt
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_TRANSFER_TO_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_TRANSFER_TO_RECEIPT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_TRANSFER_TO_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_TRANSFER_TO_RECEIPT,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_TRANSFER_TO_RECEIPT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_TRANSFER_TO_RECEIPT,
  },

  // Transfer to Customer
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_TRANSFER_TO_CUSTOMER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_TRANSFER_TO_CUSTOMER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_TRANSFER_TO_CUSTOMER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_TRANSFER_TO_CUSTOMER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_TRANSFER_TO_CUSTOMER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_TRANSFER_TO_CUSTOMER,
  },

  // Transfer to Receipt
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_WARRANTY,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_WARRANTY,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_WARRANTY,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_WARRANTY,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_WARRANTY,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_WARRANTY,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_WARRANTY,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_WARRANTY,
  },
  // History Payment Warranty
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_HISTORY_PAYMENT_WARRANTY,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_HISTORY_PAYMENT_WARRANTY,
  },
  // Gapura Management
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_GAPURA_MANAGEMENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_GAPURA_MANAGEMENT_PAGE,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_GAPURA_MANAGEMENT,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_GAPURA_MANAGEMENT_PAGE,
  },

  // Payment Warranty Partner
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.VIEW_PAYMENT_WARRANTY_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.VIEW_PAYMENT_WARRANTY_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.DETAIL_PAYMENT_WARRANTY_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.DETAIL_PAYMENT_WARRANTY_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.CREATE_PAYMENT_WARRANTY_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.CREATE_PAYMENT_WARRANTY_PARTNER,
  },
  {
    path: RECEIPT_AND_COLLECTION_ROUTES.UPDATE_PAYMENT_WARRANTY_PARTNER,
    element: RECEIPT_AND_COLLECTION_ELEMENTS.UPDATE_PAYMENT_WARRANTY_PARTNER,
  },
];
