import moment from "moment";
import { hasValue, renderColumn } from "../../../../utils";
import { getColumnSearchPropsUseFilteredValueFE } from "../../../../utils/getColumnSearchProps";

const sorter = (fieldSort, a, b) => {
  const handleDataSort = (obj) => {
    switch (fieldSort) {
      default:
        return obj[fieldSort] ? String(obj[fieldSort]).toLowerCase() : "";
    }
  };
  const fa = handleDataSort(a);
  const fb = handleDataSort(b);
  return fa.localeCompare(fb);
};

const col = (
  title,
  dataIndex,
  search,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch,
  align = null,
) => ({
  title,
  dataIndex,
  ...(align ? { align } : {}),
  sorter: (a, b) => sorter(dataIndex, a, b),
  filteredValue: search?.[dataIndex] ? [search[dataIndex]] : null,
  ...getColumnSearchPropsUseFilteredValueFE(
    search,
    dataIndex,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    true,
  ),
  render: (text) =>
    renderColumn(
      dataIndex,
      hasValue(search[dataIndex]),
      searchText,
      text,
      false,
      "input",
      search,
    ),
});

export const columnsGenerateInvoice = (
  search,
  page = 1,
  pageSize = 10,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
) => [
  {
    title: "NO",
    align: "center",
    width: 60,
    render: (text, object, index) => (page - 1) * pageSize + index + 1,
  },
  col(
    "BILLING CODE",
    "billingCode",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "BILLING CYCLE",
    "billingCycle",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "BILLING PERIOD",
    "billingPeriod",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "CUSTOMER NUMBER",
    "customerNumber",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "CUSTOMER NAME",
    "customerName",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "ACCOUNT NUMBER",
    "accountNumber",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "ACCOUNT NAME",
    "accountName",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "ACCOUNT GROUP TYPE",
    "accountGroupType",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "ACCOUNT TYPE",
    "accountType",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "CLASSIFICATION TYPE",
    "classificationType",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "SERVICE TYPE",
    "serviceType",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "SOR",
    "sor",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "COST CENTER",
    "costCenter",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "ACCOUNT SEGMENT",
    "accountSegment",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "METER READING CODE",
    "meterReadingCode",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "ACCOUNT STATUS",
    "accountStatus",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
  col(
    "CUSTOMER MANAGEMENT",
    "customerManagement",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "CORPORATE CUSTOMER",
    "corporateCustomer",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "PRODUCT",
    "product",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
  ),
  col(
    "TIME UNIT",
    "timeUnit",
    search,
    searchInput,
    searchedColumn,
    searchText,
    handleSearch,
    "center",
  ),
];

