.runner-tag:
  neuron:
    - docker
    - internal

stages:
  - pre-build
  - sq-check
  - validate
  - build
  - publish
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SONAR_HOST_URL: "https://sonar.neuronworks.co.id"
  SONAR_SOURCES: "./"
  SCAN_SOURCES: "./"
  APP_NAME: 'pgn-billing-fe-services'
  RP_HOST_URL: 'https://qualiview.neuron.id'
  SQ_CHECK_IMAGE: 'registry.neuron.id/pub/tools-testing:reportingTools-latest'
  IMAGE_DEPDENCY_CHECK: 'registry.gitlab.com/gitlab-ci-utils/docker-dependency-check:latest'
  PROJECT_OPS: 'devops/ops-repository'


# ---------------------------------------------- Rules Pipeline -----------------------------------------------------
.dev_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(?i)^testing-rbip$/ && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web")'
      variables:
        ENV_SERVER: "development"


.demo_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(?i)^demo$/ && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web")'
      variables:
        ENV_SERVER: "demo"


.staging_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(?i)^staging-qa$/ && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web")'
      variables:
        ENV_SERVER: "staging"


.preprod_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(?i)^pre-production$/ && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web")'
      variables:
        ENV_SERVER: "pre-production"


.release_rules:
  rules:
    - if: '($CI_COMMIT_TAG =~ /^v.*$/) || ($CI_COMMIT_BRANCH == "000-tempolary" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"))'
      variables:
        ENV_SERVER: "production"

.ci_rules:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(?i)^testing-rbip$/ && $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENV_SERVER: "development"
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(?i)^staging-qa$/ && $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENV_SERVER: "staging"
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(?i)^main$/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENV_SERVER: "to-prod"
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(?i)^pre-production$/ && $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        ENV_SERVER: "pre-production"

# ------------------------------------------------ Template -------------------------------------------------------
include:
  - project: template/devops
    ref: main
    file:
      - continuous-integration.yaml
      - prebuild-stage.yaml
      - publish-stage.yaml 
      - rules.yaml
      - trigger.yaml

# ----------------------------------------- Pre Build --------------------------------------------------------------
prepare-version:
  stage: pre-build
  extends: .prepare-version
  tags: !reference [.runner-tag, neuron]
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.release_rules, rules]
    - !reference [.preprod_rules, rules]
    - !reference [.multibranch_rules, rules]
    - !reference [.ci_rules, rules]

prebuild-pgnbill-fe:
  stage: pre-build
  extends: .prebuild-node
  tags: !reference [.runner-tag, neuron]
  needs: ['prepare-version']

# ----------------------------------------- Build ------------------------------------------------------------------
build-pgnbill-fe:
  stage: build
  extends: .build-node
  tags: !reference [.runner-tag, neuron]
  needs: ['prepare-version', 'prebuild-pgnbill-fe']

publish-pgnbill-fe:
  stage: publish
  extends: .build-app-gitlab
  variables:
    DOCKERFILE_NAME: Dockerfile
  needs: ['prepare-version', 'prebuild-pgnbill-fe', 'build-pgnbill-fe']
  tags: !reference [.runner-tag, neuron]

# ------------------------------------------- Trigger Deploy -------------------------------------------------------
deploy-pgnbill-fe:
  variables:
    APP_VERSION : $APP_VERSION
  stage: deploy
  needs:
    ['prepare-version', 'prebuild-pgnbill-fe', 'build-pgnbill-fe', 'publish-pgnbill-fe']
  extends: .trigger-project