---
# Source: pgn-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgn-frontend
  namespace: energy-development
  labels:
    helm.sh/chart: pgn-frontend-0.1.0
    app.kubernetes.io/name: pgn-frontend
    app.kubernetes.io/instance: pgn-frontend
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgn-frontend
      app.kubernetes.io/instance: pgn-frontend
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: pgn-frontend
        rollout-timestamp: "2025-07-21 10:28:38.9666111 +0700 +07 m=+0.733699501"
        meta.helm.sh/release-namespace: "energy-development"
      labels:
        helm.sh/chart: pgn-frontend-0.1.0
        app.kubernetes.io/name: pgn-frontend
        app.kubernetes.io/instance: pgn-frontend
        app.kubernetes.io/version: latest
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: pgnregcred
      serviceAccountName: energy-vault
      securityContext:
        null
      containers:
        - name: pgn-frontend
          securityContext:
            null
          image: "registry.pgn.co.id/billing-dev/pgn-frontend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: "0.25"
              memory: 1Gi
            requests:
              cpu: "0.25"
              memory: 512Mi
