import { Tooltip } from "antd";
import moment from "moment";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";
import { dateFormatting, renderColumn } from "../../../../../../utils";
import SVGIcon from "../../../../../../assets/Icon/index";

export const tableApprovalWarranty = (
  search,
  page,
  pageSize,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch,
  handleDetail
) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "left",
    render: (text, object, index) => (page - 1) * pageSize + index + 1,
  },
  {
    key: "warrantyCode",
    title: "PAYMENT GUARANTEE",
    dataIndex: "warrantyCode",
    width: 200,
    align: "center",
    ...getColumnSearchPropsUseFilteredValue(search, "warrantyCode", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    width: 200,
    ...getColumnSearchPropsUseFilteredValue(search, "costCenter", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 200,
    align: "center",
    ...getColumnSearchPropsUseFilteredValue(search, "accountNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 250,
    ...getColumnSearchPropsUseFilteredValue(search, "accountName", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "saNumber",
    title: "SA NUMBER",
    dataIndex: "saNumber",
    width: 150,
    ...getColumnSearchPropsUseFilteredValue(search, "saNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 150,
    align: "center",
    ...getColumnSearchPropsUseFilteredValue(search, "customerNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 250,
    ...getColumnSearchPropsUseFilteredValue(search, "customerName", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerSegment",
    title: "CUSTOMER SEGMENT",
    dataIndex: "customerSegment",
    width: 180,
    ...getColumnSearchPropsUseFilteredValue(search, "customerSegment", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerGroup",
    title: "CUSTOMER GROUP",
    dataIndex: "customerGroup",
    width: 180,
    ...getColumnSearchPropsUseFilteredValue(search, "customerGroup", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "type",
    title: "TYPE",
    dataIndex: "type",
    width: 120,
    align: "center",
    ...getColumnSearchPropsUseFilteredValue(search, "type", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "warrantyType",
    title: "WARRANTY TYPE",
    dataIndex: "warrantyType",
    width: 150,
    ...getColumnSearchPropsUseFilteredValue(search, "warrantyType", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "issuerBank",
    title: "ISSUER",
    dataIndex: "issuerBank",
    width: 150,
    ...getColumnSearchPropsUseFilteredValue(search, "issuerBank", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "issuerBranch",
    title: "ISSUER BRANCH",
    dataIndex: "issuerBranch",
    width: 150,
    ...getColumnSearchPropsUseFilteredValue(search, "issuerBranch", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "documentNumber",
    title: "DOCUMENT NUMBER",
    dataIndex: "documentNumber",
    width: 200,
    ...getColumnSearchPropsUseFilteredValue(search, "documentNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    width: 100,
    ...getColumnSearchPropsUseFilteredValue(search, "currency", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currencyBalance",
    title: "BALANCE",
    dataIndex: "currencyBalance",
    width: 150,
    align: "right",
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "rateType",
    title: "RATE TYPE",
    dataIndex: "rateType",
    width: 120,
    ...getColumnSearchPropsUseFilteredValue(search, "rateType", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "rateDate",
    title: "RATE DATE",
    dataIndex: "rateDate",
    width: 150,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "rate",
    title: "RATE",
    dataIndex: "rate",
    width: 120,
    align: "right",
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "equivalent",
    title: "EQV. BALANCE",
    dataIndex: "equivalent",
    width: 150,
    align: "right",
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "mutationDate",
    title: "MUTATION DATE",
    dataIndex: "mutationDate",
    width: 150,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "effectiveDate",
    title: "EFFECTIVE DATE",
    dataIndex: "effectiveDate",
    width: 150,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "expiringDate",
    title: "EXPIRING DATE",
    dataIndex: "expiringDate",
    width: 150,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "endClaimDate",
    title: "END DATE CLAIM",
    dataIndex: "endClaimDate",
    width: 150,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "claimPeriodTermType",
    title: "CLAIM TERM TYPE",
    dataIndex: "claimPeriodTermType",
    width: 150,
    ...getColumnSearchPropsUseFilteredValue(search, "claimPeriodTermType", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "claimPeriodTermValue",
    title: "CLAIM TERM VALUE",
    dataIndex: "claimPeriodTermValue",
    width: 150,
    align: "right",
  },
  {
    key: "description",
    title: "DESCRIPTION",
    dataIndex: "description",
    width: 300,
    ...getColumnSearchPropsUseFilteredValue(search, "description", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "status",
    title: "STATUS",
    dataIndex: "status",
    width: 120,
    align: "center",
    fixed: "right",
    render: (text) => renderColumn('status', searchedColumn, searchText, text, false, 'status', search)
  },
  {
    key: "approvalStatus",
    title: "STATUS APPROVAL",
    dataIndex: "approvalStatus",
    width: 150,
    align: "center",
    fixed: "right",
    render: (text) => renderColumn('approvalStatus', searchedColumn, searchText, text, false, 'status', search)
  },
];
