import { element } from "prop-types";
import { ACCOUNT_MANAGEMENT_ELEMENTS } from "./customer_account_elements";
import { ACCOUNT_MANAGEMENT_ROUTES } from "./customer_account_routes";

export const account_management = [
  // Customer
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_CUSTOMER,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_CUSTOMER_PAGE,
    authority: "20",
  },

  // Account Standard
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_ACCOUNT_STANDARD,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_ACCOUNT_STANDARD_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_ACCOUNT_STANDARD,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_ACCOUNT_STANDARD_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_STANDARD,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_STANDARD_PAGE,
  },

  // Account Onetime
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_ACCOUNT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_ACCOUNT_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_ACCOUNT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_ACCOUNT_ONETIME_PAGE,
  },

  // Detail Service Agreement
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_SERVICE_AGREEMENT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_SERVICE_AGREEMENT_PAGE,
  },

  // ================================
  //  START SERVICE AGREEMENT
  // ================================
  // Create Service Agreement - MAIN
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_SERVICE_AGREEMENT_MAIN,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_SERVICE_AGREEMENT_MAIN_PAGE,
  },

  // Create Service Agreement - ADDON
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_SERVICE_AGREEMENT_ADDON,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_SERVICE_AGREEMENT_ADDON_PAGE,
  },

  // Create Service Agreement - AMANDEMEN
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_SERVICE_AGREEMENT_AMANDEMEN,
    element:
      ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_SERVICE_AGREEMENT_AMANDEMEN_PAGE,
  },

  // Update Service Agreement - MAIN
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_SERVICE_AGREEMENT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_SERVICE_AGREEMENT_PAGE,
  },

  // // Update Service Agreement - ADDON
  // {
  //   path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_SERVICE_AGREEMENT_ADDON,
  //   element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_SERVICE_AGREEMENT_ADDON_PAGE,
  // },

  // // Update Service Agreement - AMANDEMEN
  // {
  //   path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_SERVICE_AGREEMENT_AMANDEMEN,
  //   element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_SERVICE_AGREEMENT_AMANDEMEN_PAGE,
  // },
  // =============================
  //  END SERVICE AGREEMENT
  // ==============================


  // DETAIL PAYMENT RELATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_PAYMENT_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_PAYMENT_RELATION_PAGE,
  },

  // CREATE PAYMENT REALATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_PAYMENT_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_PAYMENT_RELATION_PAGE,
  },

  // UPDATE PAYMENT REALATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_PAYMENT_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_PAYMENT_RELATION_PAGE,
  },

  // PAYMENT RELATION ONE TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_PAYMENT_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_PAYMENT_RELATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_PAYMENT_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_PAYMENT_RELATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_PAYMENT_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_PAYMENT_RELATION_ONETIME_PAGE,
  },

  // DETAIL INVOICE RELATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_INVOICE_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_INVOICE_RELATION_PAGE,
  },

  // CREATE INVOICE REALATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_INVOICE_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_INVOICE_RELATION_PAGE,
  },

  // UPDATE INVOICE REALATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_INVOICE_RELATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_INVOICE_RELATION_PAGE,
  },

  // INVOICE RELATION ONE TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_INVOICE_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_INVOICE_RELATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_INVOICE_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_INVOICE_RELATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_INVOICE_RELATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_INVOICE_RELATION_ONETIME_PAGE,
  },

  // CREATE ACCOUNT ADDRESS STANDARD
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_ADDRESS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_ADDRESS_PAGE,
  },

  // UPDATE ACCOUNT ADDRESS STANDARD
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_ADDRESS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_ADDRESS_PAGE,
  },

  // CREATE ACCOUNT ADDRESS ONE-TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_ADDRESS_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_ADDRESS_PAGE,
  },

  // UPDATE ACCOUNT ADDRESS ONE-TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_ADDRESS_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_ADDRESS_PAGE,
  },

  // CREATE ACCOUNT CONTACT STANDARD
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_CONTACT_PAGE,
  },

  // UPDATE ACCOUNT CONTACT STANDARD
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_CONTACT_PAGE,
  },
  // CREATE ACCOUNT CONTACT ONETIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNT_CONTACT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNT_CONTACT_PAGE,
  },

  // UPDATE ACCOUNT CONTACT ONETIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_CONTACT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_CONTACT_PAGE,
  },

  // Gas Sources
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_GAS_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_GAS_SOURCE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_GAS_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_GAS_SOURCE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_GAS_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_GAS_SOURCE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_GAS_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_GAS_SOURCE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPLOAD_GAS_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPLOAD_GAS_SOURCE,
  },

  // MULTI DESTINATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_MULTI_DESTINATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_MULTI_DESTINATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_MULTI_DESTINATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_MULTI_DESTINATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_MULTI_DESTINATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_MULTI_DESTINATION_PAGE,
  },

  // MULTI DESTINATION ONE TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_MULTI_DESTINATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_MULTI_DESTINATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_MULTI_DESTINATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_MULTI_DESTINATION_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_MULTI_DESTINATION_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_MULTI_DESTINATION_ONETIME_PAGE,
  },

  //PREMISE
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_PREMISE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_PREMISE_PAGE,
  },

  //SERVICE POINT
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_SERVICE_POINT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_SERVICE_POINT_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ASSET_POINT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ASSET_SERVICE_POINT_PAGE,
  },

  //UPDATE ACCOUNT STANDARD
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_STANDARD,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_STANDARD_PAGE,
  },

  //UPDATE ACCOUNT ONETIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNT_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNT_STANDARD_PAGE,
  },

  //RELATIONSHIP
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_RELATIONSHIP,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_RELATIONSHIP_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_RELATIONSHIP,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_RELATIONSHIP_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_RELATIONSHIP,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_RELATIONSHIP_PAGE,
  },

  //RELATIONSHIP ONE TIME
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_RELATIONSHIP_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_RELATIONSHIP_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_RELATIONSHIP_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_RELATIONSHIP_ONETIME_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_RELATIONSHIP_ONETIME,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_RELATIONSHIP_ONETIME_PAGE,
  },

  //SA APPROVE REJECT TOS
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.APPROVE_REJECT_TOS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.APPROVE_OR_REJECT_TOS_PAGE,
  },

  //CUSTOMER
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_CUSTOMER,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_CUSTOMER_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_CUSTOMER,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_CUSTOMER_PAGE,
  },

  //TOS Submission
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_TOS_SUBMISSION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_TOS_SUBMISSION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_TOS_SUBMISSION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_TOS_SUBMISSION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_TOS_SUBMISSION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_TOS_SUBMISSION_PAGE,
  },

  // Raw Material Source
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_RAW_MATERIAL_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_RAW_MATERIAL_SOURCE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_RAW_MATERIAL_SOURCE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_RAW_MATERIAL_SOURCE_PAGE,
  },
  
  // Product Distribution
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_PRODUCT_DISTRIBUTION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_PRODUCT_DISTRIBUTION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_PRODUCT_DISTRIBUTION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_PRODUCT_DISTRIBUTION_PAGE,
  },

  // MASTER DATA

  //METER READING
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_METER_READING_CODES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_METER_READING_CODE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPLOAD_METER_READING_CODES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPLOAD_METER_READING_CODE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_METER_READING_CODES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_METER_READING_CODE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_METER_READING_CODES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_METER_READING_CODE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_METER_READING_CODES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DET,
  },
  //CONTACT
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_CONTACT_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_CONTACT_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_CONTACT_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_CONTACT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_CONTACT_PAGE,
  },
  //LOCATIONS
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_LOCATIONS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_LOCATIONS_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPLOAD_LOCATIONS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPLOAD_LOCATIONS_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_LOCATIONS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_LOCATIONS_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_LOCATIONS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_LOCATIONS_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_LOCATIONS,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_LOCATIONS_PAGE,
  },
  // ADDRESSES
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_ADDRESSES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_ADDRESSES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPLOAD_ADDRESSES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPLOAD_ADDRESSES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ADDRESSES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ADDRESSES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ADDRESSES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ADDRESSES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_ADDRESSES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_ADDRESSES_PAGE,
  },
  // ACCOUNTING RULES
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_ACCOUNTING_RULES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_ACCOUNTING_RULES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPLOAD_ACCOUNTING_RULES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPLOAD_ACCOUNTING_RULES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_ACCOUNTING_RULES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_ACCOUNTING_RULES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_ACCOUNTING_RULES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_ACCOUNTING_RULES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_ACCOUNTING_RULES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_ACCOUNTING_RULES_PAGE,
  },
  // LATE CHARGES
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_LATE_CHARGES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_LATE_CHARGES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_LATE_CHARGES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_LATE_CHARGES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_LATE_CHARGES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_LATE_CHARGES_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_LATE_CHARGES,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_LATE_CHARGES_PAGE,
  },
  // LATE CHARGES RULE
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_LATE_CHARGES_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_LATE_CHARGES_RULE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_LATE_CHARGES_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_LATE_CHARGES_RULE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_LATE_CHARGES_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_LATE_CHARGES_RULE_PAGE,
  },
  // TAX IMPLICATION
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_TAX_IMPLICATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_TAX_IMPLICATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_TAX_IMPLICATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_TAX_IMPLICATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_TAX_IMPLICATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_TAX_IMPLICATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_TAX_IMPLICATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_TAX_IMPLICATION_PAGE,
  },
  // TAX IMPLICATION RULE
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_TAX_IMPLICATION_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_TAX_IMPLICATION_RULE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_TAX_IMPLICATION_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_TAX_IMPLICATION_RULE_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.DETAIL_TAX_IMPLICATION_RULE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.DETAIL_TAX_IMPLICATION_RULE_PAGE,
  },

  // Gas Utilization
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_GAS_UTILIZATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_GAS_UTILIZATION_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_GAS_UTILIZATION,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_GAS_UTILIZATION_PAGE,
  },

  // EQUIPMENT
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_EQUIPMENT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_EQUIPMENT_PAGE,
  },
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.UPDATE_EQUIPMENT,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.UPDATE_EQUIPMENT_PAGE,
  },

  // ================================
  //  SERVICE REQUEST
  // ================================
  // View Detail Service Request
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.VIEW_DETAIL_SERVICE_REQUEST,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.VIEW_DETAIL_SERVICE_REQUEST_PAGE,
  },
  // Create Service Request
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_SERVICE_REQUEST,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_SERVICE_REQUEST_PAGE,
  },
  // Create Service Request Prerequisite
  {
    path: ACCOUNT_MANAGEMENT_ROUTES.CREATE_SERVICE_REQUEST_PREREQUISITE,
    element: ACCOUNT_MANAGEMENT_ELEMENTS.CREATE_SERVICE_REQUEST_PREREQUISITE_PAGE,
  },
];
