import { UnorderedListOutlined } from "@ant-design/icons";
import { Col } from "antd";

const promoHistoryRepository = {
  getPromoHistoryList: () => [
    {
      key: "1",
      no: 1,
      name: "Summer Sale",
      type: "Percentage",
      category: "Seasonal",
      criteria: "Min Purchase 100k",
      billingDate: "2024-06-15",
    },
    {
      key: "2",
      no: 2,
      name: "Winter Discount",
      type: "Fixed Amount",
      category: "Seasonal",
      criteria: "Min Purchase 200k",
      billingDate: "2024-12-15",
    },
    {
      key: "3",
      no: 3,
      name: "New Year Sale",
      type: "Percentage",
      category: "Holiday",
      criteria: "New Customer",
      billingDate: "2024-01-08",
    },
    {
      key: "4",
      no: 4,
      name: "Valentine Special",
      type: "Buy One Get One",
      category: "Holiday",
      criteria: "Couple Package",
      billingDate: "2024-02-12",
    },
    {
      key: "5",
      no: 5,
      name: "Spring Flash Sale",
      type: "Percentage",
      category: "Flash Sale",
      criteria: "Limited Time",
      billingDate: "2024-03-21",
    },
    {
      key: "6",
      no: 6,
      name: "Easter Bundle",
      type: "Bundle Discount",
      category: "Holiday",
      criteria: "Family Package",
      billingDate: "2024-03-30",
    },
    {
      key: "7",
      no: 7,
      name: "Mother's Day",
      type: "Gift Voucher",
      category: "Holiday",
      criteria: "Gift Purchase",
      billingDate: "2024-05-10",
    },
    {
      key: "8",
      no: 8,
      name: "Back to School",
      type: "Student Discount",
      category: "Education",
      criteria: "Student ID",
      billingDate: "2024-08-15",
    },
    {
      key: "9",
      no: 9,
      name: "Independence Day",
      type: "Percentage",
      category: "National",
      criteria: "All Purchase",
      billingDate: "2024-08-17",
    },
    {
      key: "10",
      no: 10,
      name: "Halloween Spooky",
      type: "Costume Discount",
      category: "Holiday",
      criteria: "Halloween Items",
      billingDate: "2024-10-28",
    },
    {
      key: "11",
      no: 11,
      name: "Black Friday",
      type: "Mega Sale",
      category: "Shopping Event",
      criteria: "Everything",
      billingDate: "2024-11-29",
    },
    {
      key: "12",
      no: 12,
      name: "Cyber Monday",
      type: "Online Exclusive",
      category: "Shopping Event",
      criteria: "Online Only",
      billingDate: "2024-12-02",
    },
    {
      key: "13",
      no: 13,
      name: "Christmas Joy",
      type: "Gift Wrap Free",
      category: "Holiday",
      criteria: "Gift Items",
      billingDate: "2024-12-20",
    },
    {
      key: "14",
      no: 14,
      name: "Year End Clearance",
      type: "Clearance Sale",
      category: "Clearance",
      criteria: "Old Stock",
      billingDate: "2024-12-28",
    },
    {
      key: "15",
      no: 15,
      name: "Loyalty Reward",
      type: "Points Multiplier",
      category: "Loyalty",
      criteria: "Member Points",
      billingDate: "2024-06-30",
    },
    {
      key: "16",
      no: 16,
      name: "Birthday Special",
      type: "Birthday Discount",
      category: "Personal",
      criteria: "Birthday Month",
      billingDate: "2024-07-15",
    },
    {
      key: "17",
      no: 17,
      name: "First Purchase",
      type: "Welcome Bonus",
      category: "New Customer",
      criteria: "First Time Buyer",
      billingDate: "2024-01-05",
    },
    {
      key: "18",
      no: 18,
      name: "Referral Bonus",
      type: "Referral Reward",
      category: "Referral",
      criteria: "Successful Referral",
      billingDate: "2024-02-28",
    },
    {
      key: "19",
      no: 19,
      name: "Bulk Purchase",
      type: "Volume Discount",
      category: "Wholesale",
      criteria: "Min Quantity 10",
      billingDate: "2024-03-10",
    },
    {
      key: "20",
      no: 20,
      name: "Weekend Special",
      type: "Weekend Only",
      category: "Time Limited",
      criteria: "Weekend Purchase",
      billingDate: "2024-04-06",
    },
    {
      key: "21",
      no: 21,
      name: "Morning Deal",
      type: "Early Bird",
      category: "Time Limited",
      criteria: "Before 10 AM",
      billingDate: "2024-05-20",
    },
    {
      key: "22",
      no: 22,
      name: "Late Night Sale",
      type: "Night Owl",
      category: "Time Limited",
      criteria: "After 9 PM",
      billingDate: "2024-06-05",
    },
    {
      key: "23",
      no: 23,
      name: "Senior Citizen",
      type: "Age Discount",
      category: "Demographics",
      criteria: "Age 60+",
      billingDate: "2024-07-25",
    },
    {
      key: "24",
      no: 24,
      name: "Military Appreciation",
      type: "Service Discount",
      category: "Service",
      criteria: "Military ID",
      billingDate: "2024-08-10",
    },
    {
      key: "25",
      no: 25,
      name: "Teacher Discount",
      type: "Profession Discount",
      category: "Education",
      criteria: "Teacher ID",
      billingDate: "2024-09-15",
    },
    {
      key: "26",
      no: 26,
      name: "Healthcare Worker",
      type: "Hero Discount",
      category: "Service",
      criteria: "Healthcare ID",
      billingDate: "2024-10-05",
    },
    {
      key: "27",
      no: 27,
      name: "Flash Mob Sale",
      type: "Social Media",
      category: "Social",
      criteria: "Social Share",
      billingDate: "2024-01-16",
    },
    {
      key: "28",
      no: 28,
      name: "Review Reward",
      type: "Review Bonus",
      category: "Feedback",
      criteria: "Product Review",
      billingDate: "2024-11-10",
    },
    {
      key: "29",
      no: 29,
      name: "App Exclusive",
      type: "Mobile Only",
      category: "Platform",
      criteria: "Mobile App",
      billingDate: "2024-12-05",
    },
    {
      key: "30",
      no: 30,
      name: "Email Subscriber",
      type: "Newsletter Bonus",
      category: "Subscription",
      criteria: "Email Signup",
      billingDate: "2024-01-20",
    },
    {
      key: "31",
      no: 31,
      name: "VIP Member",
      type: "VIP Exclusive",
      category: "Membership",
      criteria: "VIP Status",
      billingDate: "2024-02-14",
    },
    {
      key: "32",
      no: 32,
      name: "Gold Member",
      type: "Gold Tier",
      category: "Membership",
      criteria: "Gold Status",
      billingDate: "2024-03-18",
    },
    {
      key: "33",
      no: 33,
      name: "Silver Member",
      type: "Silver Tier",
      category: "Membership",
      criteria: "Silver Status",
      billingDate: "2024-04-22",
    },
    {
      key: "34",
      no: 34,
      name: "Bronze Member",
      type: "Bronze Tier",
      category: "Membership",
      criteria: "Bronze Status",
      billingDate: "2024-05-26",
    },
    {
      key: "35",
      no: 35,
      name: "Group Booking",
      type: "Group Discount",
      category: "Group",
      criteria: "Min 5 People",
      billingDate: "2024-06-18",
    },
    {
      key: "36",
      no: 36,
      name: "Corporate Deal",
      type: "B2B Discount",
      category: "Corporate",
      criteria: "Company Purchase",
      billingDate: "2024-07-22",
    },
    {
      key: "37",
      no: 37,
      name: "Eco Friendly",
      type: "Green Discount",
      category: "Environmental",
      criteria: "Eco Products",
      billingDate: "2024-04-25",
    },
    {
      key: "38",
      no: 38,
      name: "Local Community",
      type: "Community Support",
      category: "Local",
      criteria: "Local Resident",
      billingDate: "2024-08-30",
    },
    {
      key: "39",
      no: 39,
      name: "Charity Partner",
      type: "Donation Match",
      category: "Charity",
      criteria: "Charity Donation",
      billingDate: "2024-09-12",
    },
    {
      key: "40",
      no: 40,
      name: "Sports Team Fan",
      type: "Fan Discount",
      category: "Sports",
      criteria: "Team Merchandise",
      billingDate: "2024-10-16",
    },
    {
      key: "41",
      no: 41,
      name: "Music Festival",
      type: "Event Tie-in",
      category: "Entertainment",
      criteria: "Festival Ticket",
      billingDate: "2024-07-18",
    },
    {
      key: "42",
      no: 42,
      name: "Art Gallery",
      type: "Cultural Discount",
      category: "Culture",
      criteria: "Art Purchase",
      billingDate: "2024-11-20",
    },
    {
      key: "43",
      no: 43,
      name: "Food Festival",
      type: "Culinary Event",
      category: "Food",
      criteria: "Food Items",
      billingDate: "2024-09-15",
    },
    {
      key: "44",
      no: 44,
      name: "Book Club",
      type: "Literary Discount",
      category: "Education",
      criteria: "Book Purchase",
      billingDate: "2024-12-10",
    },
    {
      key: "45",
      no: 45,
      name: "Fitness Challenge",
      type: "Health Reward",
      category: "Health",
      criteria: "Fitness Goal",
      billingDate: "2024-01-30",
    },
    {
      key: "46",
      no: 46,
      name: "Travel Partner",
      type: "Travel Discount",
      category: "Travel",
      criteria: "Travel Booking",
      billingDate: "2024-02-25",
    },
    {
      key: "47",
      no: 47,
      name: "Pet Owner",
      type: "Pet Discount",
      category: "Pet",
      criteria: "Pet Products",
      billingDate: "2024-03-28",
    },
    {
      key: "48",
      no: 48,
      name: "Gardening Club",
      type: "Garden Discount",
      category: "Hobby",
      criteria: "Garden Supplies",
      billingDate: "2024-04-15",
    },
    {
      key: "49",
      no: 49,
      name: "Tech Enthusiast",
      type: "Tech Discount",
      category: "Technology",
      criteria: "Tech Products",
      billingDate: "2024-05-12",
    },
    {
      key: "50",
      no: 50,
      name: "Anniversary Sale",
      type: "Milestone Event",
      category: "Company",
      criteria: "All Products",
      billingDate: "2024-06-20",
    },
  ],
  getColumns: () => [
    {
      title: "No",
      dataIndex: "no",
      key: "no",
      width: 60,
    },
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "Type",
      dataIndex: "type",
      key: "type",
    },
    {
      title: "Category",
      dataIndex: "category",
      key: "category",
    },
    {
      title: "Criteria",
      dataIndex: "criteria",
      key: "criteria",
    },
    {
      title: "Billing Date",
      dataIndex: "billingDate",
      key: "billingDate",
    },
    {
      title: "Action",
      dataIndex: "action",
      key: "action",
      render: () => (
        <Col span={24} className="text-center">
          <UnorderedListOutlined />
        </Col>
      ),
    },
  ],
};
export default promoHistoryRepository;
