import {
  hasValue,
  renderColumn,
  renderDateColumn,
} from "../../../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";

export const columnsUsage = (
  search,
  page = 1,
  pageSize = 10,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 60,
    render: (text, object, index) => (page - 1) * pageSize + index + 1,
  },
  {
    key: "period",
    title: "Billing Period",
    width: 150,
    sorter: true,
    isClassification: true,
    dataIndex: "period",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "period",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "datePeriod",
    ),
    render: (text) =>
      renderDateColumn(
        "period",
        hasValue(search["period"]),
        searchText,
        text,
        "datePeriod",
        search,
      ),
  },
  {
    key: "assetSerialNumber",
    title: "ASSET SERIAL NUMBER",
    dataIndex: "assetSerialNumber",
    width: 190,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "assetSerialNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "assetSerialNumber",
        hasValue(search["assetSerialNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "assetType",
    title: "ASSET TYPE",
    dataIndex: "assetType",
    width: 130,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "assetType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "assetType",
        hasValue(search["assetType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "measDate",
    title: "READING DATE",
    sorter: true,
    isClassification: true,
    dataIndex: "measDate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "measDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "datetime",
    ),
    render: (text) =>
      renderDateColumn(
        "measDate",
        hasValue(search["measDate"]),
        searchText,
        text,
        "datetime",
        search,
      ),
  },
  {
    key: "fdate",
    title: "DATE",
    width: 120,
    sorter: true,
    isClassification: true,
    dataIndex: "fdate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "fdate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "fdate",
        hasValue(search["fdate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "fhour",
    title: "HOUR",
    dataIndex: "fhour",
    width: 100,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "fhour",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "hour",
    ),
    render: (creationDate) =>
      renderColumn(
        "fhour",
        hasValue(search["fhour"]),
        searchText,
        creationDate,
        false,
        "input",
        search,
      ),
  },
  {
    key: "stream",
    title: "STREAM ID",
    dataIndex: "stream",
    width: 120,
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "stream",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "stream",
        hasValue(search["stream"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "temperature",
    title: "TEMPERATURE",
    dataIndex: "temperature",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "temperature",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "temperature",
        hasValue(search["temperature"]),
        searchText,
        text,
        false,
        "input",
        search,
        "temperatur",
      ),
  },
  {
    key: "pressure",
    title: "PRESSURE",
    dataIndex: "pressure",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "pressure",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "pressure",
        hasValue(search["pressure"]),
        searchText,
        text,
        false,
        "input",
        search,
        "tekanan",
      ),
  },
  {
    key: "correctionFactor",
    title: "CORRECTION FACTOR",
    dataIndex: "correctionFactor",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "correctionFactor",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "correctionFactor",
        hasValue(search["correctionFactor"]),
        searchText,
        text,
        false,
        "input",
        search,
        "number",
      ),
  },
  {
    key: "calorie",
    title: "CALORIE",
    dataIndex: "calorie",
    width: 150,
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "calorie",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "calorie",
        hasValue(search["calorie"]),
        searchText,
        text,
        false,
        "input",
        search,
        "number",
      ),
  },
  {
    key: "beginStand",
    title: "BEGIN STAND",
    dataIndex: "beginStand",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "beginStand",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "beginStand",
        hasValue(search["beginStand"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "endStand",
    title: "END STAND",
    dataIndex: "endStand",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "endStand",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "endStand",
        hasValue(search["endStand"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "volMeasured27",
    title: "VOLUME 27",
    dataIndex: "volMeasured27",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "volMeasured27",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "volMeasured27",
        hasValue(search["volMeasured27"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "volMeasured60",
    title: "VOLUME 60",
    dataIndex: "volMeasured60",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "volMeasured60",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "volMeasured60",
        hasValue(search["volMeasured60"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "engMeasured",
    title: "MMBTU",
    dataIndex: "engMeasured",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "engMeasured",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) => {
      const fixed =
        text && typeof text === "string" && text.startsWith(".")
          ? `0${text}`
          : text;

      return renderColumn(
        "engMeasured",
        hasValue(search["engMeasured"]),
        searchText,
        fixed,
        false,
        "input",
        search,
        "energi",
      );
    },
  },
  {
    key: "ghv",
    title: "GHV",
    dataIndex: "ghv",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "ghv",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "ghv",
        hasValue(search["ghv"]),
        searchText,
        text,
        false,
        "input",
        search,
        "ghv",
      ),
  },
  {
    key: "sources",
    sorter: true,
    title: "SOURCE",
    isClassification: true,
    dataIndex: "sources",
    ellipsis: {
      showTitle: false,
    },
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "sources",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "sources",
        hasValue(search["sources"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "taxationRowId",
    title: "TAXATION ROW ID",
    dataIndex: "taxationRowId",
    width: 180,
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "taxationRowId",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "taxationRowId",
        hasValue(search["taxationRowId"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "createdDate",
    title: "CREATION DATE",
    sorter: true,
    isClassification: true,
    dataIndex: "createdDate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "createdDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (creationDate) =>
      renderDateColumn(
        "createdDate",
        hasValue(search["createdDate"]),
        searchText,
        creationDate,
        "date",
        search,
      ),
  },
  {
    key: "approvedBy",
    title: "APPROVED BY",
    dataIndex: "approvedBy",
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "approvedBy",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "approvedBy",
        hasValue(search["approvedBy"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "volMscf",
    title: "VOLUME MSCF",
    dataIndex: "volMscf",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "volMscf",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "volMscf",
        hasValue(search["volMscf"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "uncorrectedValue",
    title: "UNCORRECTED VOL",
    dataIndex: "uncorrectedValue",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "uncorrectedValue",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "uncorrectedValue",
        hasValue(search["uncorrectedValue"]),
        searchText,
        text,
        false,
        "input",
        search,
        "volume",
      ),
  },
  {
    key: "lastUpdatedDate",
    title: "LAST UPDATE DATE",
    sorter: true,
    isClassification: true,
    dataIndex: "lastUpdatedDate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "lastUpdatedDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "lastUpdatedDate",
        hasValue(search["lastUpdatedDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "fileSource",
    title: "SOURCE",
    dataIndex: "fileSource",
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "fileSource",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
  },
  {
    key: "description",
    sorter: true,
    title: "DESCRIPTION",
    isClassification: true,
    dataIndex: "description",
    ellipsis: {
      showTitle: false,
    },
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "description",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "description",
        hasValue(search["description"]),
        searchText,
        text,
        true,
        "input",
        search,
      ),
  },
];
