import React from "react";
import { Tooltip } from "antd";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";
import {
  hasValue,
  renderColumn,
  renderDateColumn,
} from "../../../../../../utils";
import StatusComponent from "../../../../../../components/StatusComponent";

export const columnsAdjustmentInvoice = (
  page = 0,
  pageSize = 0,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  search,
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 25,
    render: (text, object, index) => index + 1,
  },
  {
    key: "invoiceNumber",
    title: "INVOICE NUMBER",
    dataIndex: "invoiceNumber",
    isClassification: true,
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "invoiceNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "invoiceNumber",
        hasValue(search["invoiceNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "correctionNumber",
    title: "CORRECTION NUMBER",
    dataIndex: "correctionNumber",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "correctionNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "correctionNumber",
        hasValue(search["correctionNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "billingCycle",
    title: "BILLING CYCLE",
    dataIndex: "billingCycle",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingCycle",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "billingCycle",
        hasValue(search["billingCycle"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "billingPeriode",
    title: "BILLING PERIOD",
    dataIndex: "billingPeriode",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingPeriode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "billingPeriode",
        hasValue(search["billingPeriode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "customerNumber",
        hasValue(search["customerNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "customerName",
        hasValue(search["customerName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "accountNumber",
        hasValue(search["accountNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "accountName",
        hasValue(search["accountName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountGroupType",
    title: "ACCOUNT GROUP TYPE",
    dataIndex: "accountGroupType",
    width: 160,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountGroupType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "accountGroupType",
        hasValue(search["accountGroupType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "sor",
    title: "SOR",
    dataIndex: "sor",
    width: 80,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "sor",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "sor",
        hasValue(search["sor"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    width: 135,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "costCenter",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "costCenter",
        hasValue(search["costCenter"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountSegment",
    title: "ACCOUNT SEGMENT",
    dataIndex: "accountSegment",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountSegment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "accountSegment",
        hasValue(search["accountSegment"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "meterReadingCode",
    title: "METER READING CODE",
    dataIndex: "meterReadingCode",
    width: 160,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "meterReadingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "meterReadingCode",
        hasValue(search["meterReadingCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  // {
  //   key: "currency",
  //   title: "CURRENCY",
  //   dataIndex: "currency",
  //   width: 100,
  //   sorter: true,
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "currency",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true
  //   ),
  //   render: (text) =>
  //     renderColumn(
  //       "currency",
  //       hasValue(search["currency"]),
  //       searchText,
  //       text,
  //       false,
  //       "input",
  //       search
  //     ),
  // },
  // {
  //   key: "totalAdjustmentAmountIdr",
  //   title: "TOTAL ADJUSTMENT AMOUNT IDR",
  //   dataIndex: "totalAdjustmentAmountIdr",
  //   width: 190,
  //   sorter: true,
  //   align: "right",
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "totalAdjustmentAmountIdr",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true
  //   ),
  //   render: (text) => {
  //     const formatted = currencyFormatting(text);
  //     return renderColumn(
  //       "totalAdjustmentAmountIdr",
  //       hasValue(search["totalAdjustmentAmountIdr"]),
  //       searchText,
  //       formatted,
  //       false,
  //       "input",
  //       search
  //     );
  //   },
  // },
  // {
  //   key: "totalAdjustmentAmountUsd",
  //   title: "TOTAL ADJUSTMENT AMOUNT USD",
  //   dataIndex: "totalAdjustmentAmountUsd",
  //   width: 190,
  //   sorter: true,
  //   align: "right",
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "totalAdjustmentAmountUsd",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true
  //   ),
  //   render: (text) => {
  //     const formatted = currencyFormatting(text);
  //     return renderColumn(
  //       "totalAdjustmentAmountUsd",
  //       hasValue(search["totalAdjustmentAmountUsd"]),
  //       searchText,
  //       formatted,
  //       false,
  //       "input",
  //       search
  //     );
  //   },
  // },
  {
    key: "termsOfPayment",
    title: "TERMS OF PAYMENT",
    dataIndex: "termsOfPayment",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "termsOfPayment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "termsOfPayment",
        hasValue(search["termsOfPayment"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "transactionDtm",
    title: "TRANSACTION DATE",
    dataIndex: "transactionDtm",
    width: 130,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "transactionDtm",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "transactionDtm",
        hasValue(search["transactionDtm"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "documentDate",
    title: "DOCUMENT DATE",
    dataIndex: "documentDate",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "documentDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "documentDate",
        hasValue(search["documentDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "dueDate",
    title: "DUE DATE",
    dataIndex: "dueDate",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "dueDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "dueDate",
        hasValue(search["dueDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "typeDueDate",
    title: "TYPE DUE DATE",
    dataIndex: "typeDueDate",
    width: 130,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "typeDueDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "typeDueDate",
        hasValue(search["typeDueDate"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "adjustmentReason",
    title: "ADJUSTMENT REASON",
    dataIndex: "adjustmentReason",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "adjustmentReason",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "adjustmentReason",
        hasValue(search["adjustmentReason"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  // {
  //   key: "rateType",
  //   title: "RATE TYPE",
  //   dataIndex: "rateType",
  //   width: 100,
  //   sorter: true,
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "rateType",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true
  //   ),
  //   render: (text) =>
  //     renderColumn(
  //       "rateType",
  //       hasValue(search["rateType"]),
  //       searchText,
  //       text,
  //       false,
  //       "input",
  //       search
  //     ),
  // },
  // {
  //   key: "rate",
  //   title: "RATE",
  //   dataIndex: "rate",
  //   width: 80,
  //   sorter: true,
  //   align: "right",
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "rate",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true
  //   ),
  //   render: (text) => {
  //     const formatted = currencyFormatting(text);
  //     return renderColumn(
  //       "rate",
  //       hasValue(search["rate"]),
  //       searchText,
  //       formatted,
  //       false,
  //       "input",
  //       search
  //     );
  //   },
  // },
  // {
  //   key: "rateDate",
  //   title: "RATE DATE",
  //   dataIndex: "rateDate",
  //   width: 100,
  //   sorter: true,
  //   ...getColumnSearchPropsUseFilteredValue(
  //     search,
  //     "rateDate",
  //     searchInput,
  //     searchedColumn,
  //     searchText,
  //     handleSearch,
  //     true,
  //     "date"
  //   ),
  //   render: (text) =>
  //     renderDateColumn(
  //       "rateDate",
  //       hasValue(search["rateDate"]),
  //       searchText,
  //       text,
  //       "date",
  //       search
  //     ),
  // },
  {
    key: "remark",
    title: "REMARK",
    dataIndex: "remark",
    width: 250,
    sorter: true,
    ellipsis: {
      showTitle: false,
    },
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "remark",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      text ? (
        <Tooltip placement="topLeft" title={text}>
          {renderColumn(
            "remark",
            hasValue(search["remark"]),
            searchText,
            text,
            true,
            "input",
            search,
          )}
        </Tooltip>
      ) : (
        ""
      ),
  },
  {
    key: "status",
    title: "STATUS",
    dataIndex: "status",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "status",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) => (
      <StatusComponent colour={text} type="status" size="small">
        {text}
      </StatusComponent>
    ),
  },
  {
    key: "statusApproval",
    title: "STATUS APPROVAL",
    dataIndex: "statusApproval",
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "statusApproval",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) => (
      <StatusComponent colour={text} type="status" size="small">
        {text}
      </StatusComponent>
    ),
  },
  {
    key: "createdBy",
    title: "CREATED BY",
    dataIndex: "createdBy",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "createdBy",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "createdBy",
        hasValue(search["createdBy"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "createdDate",
    title: "CREATED DATE",
    dataIndex: "createdDate",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "createdDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "createdDate",
        hasValue(search["createdDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "updatedBy",
    title: "UPDATED BY",
    dataIndex: "updatedBy",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "updatedBy",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
    ),
    render: (text) =>
      renderColumn(
        "updatedBy",
        hasValue(search["updatedBy"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "updatedDate",
    title: "UPDATED DATE",
    dataIndex: "updatedDate",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "updatedDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "updatedDate",
        hasValue(search["updatedDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
];
