import React from "react";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";
import { renderColumn } from "../../../../../../utils";
import { currencyFormatting } from "../../../../../../utils/formatCurrency";

export const columnsAdjustmentInvoice = (
  page = 0,
  pageSize = 0,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  search
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 15,
    render: (text, object, index) => index + 1,
  },
  {
    key: "invoiceNumber",
    title: "INVOICE NUMBER",
    dataIndex: "invoiceNumber",
    isClassification: true,
    width: 90,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "invoiceNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "adjustmentNumber",
    title: "ADJUSTMENT NUMBER",
    dataIndex: "adjustmentNumber",
    width: 100,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "adjustmentNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "type",
    title: "TYPE",
    dataIndex: "type",
    width: 60,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "type",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "billingCycle",
    title: "BILLING CYCLE",
    dataIndex: "billingCycle",
    width: 70,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingCycle",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "billingPeriod",
    title: "BILLING PERIOD",
    dataIndex: "billingPeriod",
    width: 75,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingPeriod",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 90,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 110,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 85,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 100,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "accountGroupType",
    title: "ACCOUNT GROUP TYPE",
    dataIndex: "accountGroupType",
    width: 95,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountGroupType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "sor",
    title: "SOR",
    dataIndex: "sor",
    width: 50,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "sor",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    width: 75,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "costCenter",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "accountSegment",
    title: "ACCOUNT SEGMENT",
    dataIndex: "accountSegment",
    width: 90,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountSegment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "meterReadingCode",
    title: "METER READING CODE",
    dataIndex: "meterReadingCode",
    width: 95,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "meterReadingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    width: 55,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "currency",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "totalAdjustmentAmountIdr",
    title: "TOTAL ADJUSTMENT AMOUNT IDR",
    dataIndex: "totalAdjustmentAmountIdr",
    width: 120,
    sorter: true,
    align: "right",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "totalAdjustmentAmountIdr",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => (text ? currencyFormatting(text) : "-"),
  },
  {
    key: "totalAdjustmentAmountUsd",
    title: "TOTAL ADJUSTMENT AMOUNT USD",
    dataIndex: "totalAdjustmentAmountUsd",
    width: 120,
    sorter: true,
    align: "right",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "totalAdjustmentAmountUsd",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => (text ? currencyFormatting(text) : "-"),
  },
  {
    key: "termsOfPayment",
    title: "TERMS OF PAYMENT",
    dataIndex: "termsOfPayment",
    width: 90,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "termsOfPayment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "transactionDate",
    title: "TRANSACTION DATE",
    dataIndex: "transactionDate",
    width: 85,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "transactionDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "documentDate",
    title: "DOCUMENT DATE",
    dataIndex: "documentDate",
    width: 80,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "documentDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "adjustmentReason",
    title: "ADJUSTMENT REASON",
    dataIndex: "adjustmentReason",
    width: 100,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "adjustmentReason",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "rateType",
    title: "RATE TYPE",
    dataIndex: "rateType",
    width: 65,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "rateType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "rate",
    title: "RATE",
    dataIndex: "rate",
    width: 60,
    sorter: true,
    align: "right",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "rate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => (text ? currencyFormatting(text) : "-"),
  },
  {
    key: "rateDate",
    title: "RATE DATE",
    dataIndex: "rateDate",
    width: 70,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "rateDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "remark",
    title: "REMARK",
    dataIndex: "remark",
    width: 100,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "remark",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "status",
    title: "STATUS",
    dataIndex: "status",
    width: 60,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "status",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
  {
    key: "statusApproval",
    title: "STATUS APPROVAL",
    dataIndex: "statusApproval",
    width: 80,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "statusApproval",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true
    ),
    render: (text) => renderColumn(text, "-"),
  },
];
