import { Tag } from "antd";


export const createSAColumns = (renderValue) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    key: "saNumber",
    title: "SA NUMBER",
    dataIndex: "saNumber",
    width: 180,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "saReferenceNumber",
    title: "SA REFERENCE NUMBER",
    dataIndex: "saReferenceNumber",
    width: 200,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "saDate",
    title: "SA DATE",
    dataIndex: "saDate",
    width: 180,
    isClassification: true,
    render: (val) => {
      if (!val) return "";
      const date = new Date(val);
      return date.toLocaleDateString('id-ID', {
        year: 'numeric',
        month: 'short',
        day: '2-digit'
      });
    },
  },
  {
    key: "commitmentDate",
    title: "COMMITMENT DATE",
    dataIndex: "commitmentDate",
    width: 180,
    isClassification: true,
    render: (val) => {
      if (!val) return "";
      const date = new Date(val);
      return date.toLocaleDateString('id-ID', {
        year: 'numeric',
        month: 'short',
        day: '2-digit'
      });
    },
  },
  {
    key: "invoiceTemplate",
    title: "INVOICE TEMPLATE",
    dataIndex: "invoiceTemplate",
    width: 200,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "pjbgType",
    title: "PJBG TYPE",
    dataIndex: "pjbgType",
    width: 120,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "saServiceType",
    title: "SA SERVICE TYPE",
    dataIndex: "saServiceType",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "saType",
    title: "SA TYPE",
    dataIndex: "saType",
    width: 120,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "termOfPayment",
    title: "TERM OF PAYMENT",
    dataIndex: "termOfPayment",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "pricingRule",
    title: "PRICING RULE",
    dataIndex: "pricingRule",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "productName",
    title: "PRODUCT NAME",
    dataIndex: "productName",
    width: 300,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "productType",
    title: "PRODUCT TYPE",
    dataIndex: "productType",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "ppnTaxImp",
    title: "PPN TAX IMP",
    dataIndex: "ppnTaxImp",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "pphTaxImp",
    title: "PPH TAX IMP",
    dataIndex: "pphTaxImp",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
  {
    key: "mpricingCode",
    title: "PRICING CODE",
    dataIndex: "mpricingCode",
    width: 150,
    isClassification: true,
    render: renderValue,
  },
];

export const createUsageColumns = (renderValue) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    key: "measDate",
    title: "MEAS DATE",
    dataIndex: "measDate",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "assetSerialNum",
    title: "ASSET SERIAL",
    dataIndex: "assetSerialNum",
    width: 130,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "assetType",
    title: "ASSET TYPE",
    dataIndex: "assetType",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "stream",
    title: "STREAM",
    dataIndex: "stream",
    width: 100,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "temperature",
    title: "TEMPERATURE",
    dataIndex: "temperature",
    width: 120,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "pressure",
    title: "PRESSURE",
    dataIndex: "pressure",
    width: 120,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "correctionFactor",
    title: "CORRECTION FACTOR",
    dataIndex: "correctionFactor",
    width: 150,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "calorie",
    title: "CALORIE",
    dataIndex: "calorie",
    width: 120,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "beginStand",
    title: "BEGIN STAND",
    dataIndex: "beginStand",
    width: 130,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "endStand",
    title: "END STAND",
    dataIndex: "endStand",
    width: 130,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "engMeasured",
    title: "ENG MEASURED",
    dataIndex: "engMeasured",
    width: 150,
    isNumber:true,
    render: (val) =>
      val ? parseFloat(val).toLocaleString("en-US", { maximumFractionDigits: 4 }) : "",
  },
  {
    key: "ghv",
    title: "GHV",
    dataIndex: "ghv",
    width: 120,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "description",
    title: "DESCRIPTION",
    dataIndex: "description",
    width: 200,
    render: renderValue,
  },
  {
    key: "taxation",
    title: "TAXATION",
    dataIndex: "taxation",
    width: 100,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "volMeasured27",
    title: "VOL MEASURED 27",
    dataIndex: "volMeasured27",
    width: 150,
    isNumber:true,
    render: (val) => (val ? parseFloat(val).toLocaleString() : ""),
  },
  {
    key: "volMeasured60",
    title: "VOL MEASURED 60",
    dataIndex: "volMeasured60",
    width: 150,
    isNumber:true,
    render: (val) => (val ? parseFloat(val).toLocaleString() : ""),
  },
  {
    key: "volMscf",
    title: "VOL MSCF",
    dataIndex: "volMscf",
    width: 150,
    isNumber:true,
    render: (val) => (val ? parseFloat(val).toLocaleString() : ""),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "usageInitCode",
    title: "INIT CODE",
    dataIndex: "usageInitCode",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "energy",
    title: "ENERGY",
    dataIndex: "energy",
    width: 150,
    isNumber:true,
    render: (val) =>
      val ? parseFloat(val).toLocaleString("en-US", { maximumFractionDigits: 4 }) : "",
  },
  {
    key: "uncorrectedValue",
    title: "UNCORRECTED VALUE",
    dataIndex: "uncorrectedValue",
    width: 150,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "ratingCode",
    title: "RATING CODE",
    dataIndex: "ratingCode",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
];

export const createTaxColumns = (renderValue) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    key: "category",
    title: "CATEGORY",
    dataIndex: "category",
    width: 100,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "taxImpName",
    title: "TAX IMP NAME",
    dataIndex: "taxImpName",
    isClassification:true,
    width: 300,
    render: renderValue,
  },
  {
    key: "serviceType",
    title: "SERVICE TYPE",
    dataIndex: "serviceType",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "impType",
    title: "IMP TYPE",
    dataIndex: "impType",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "gunggung",
    title: "GUNGGUNG",
    dataIndex: "gunggung",
    width: 100,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "ratingCode",
    title: "RATING CODE",
    dataIndex: "ratingCode",
    isClassification:true,
    width: 150,
    render: renderValue,
  },
];

export const createBillingBucketColumns = (renderValue) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    key: "bucketCode",
    title: "BUCKET CODE",
    dataIndex: "bucketCode",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "bucketName",
    title: "BUCKET NAME",
    dataIndex: "bucketName",
    isClassification:true,
    width: 200,
    render: renderValue,
  },
  {
    key: "bucketPriority",
    title: "BUCKET PRIORITY",
    dataIndex: "bucketPriority",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "validStartDate",
    title: "VALID START DATE",
    dataIndex: "validStartDate",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "validEndDate",
    title: "VALID END DATE",
    dataIndex: "validEndDate",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
];

export const createBillingItemColumns = (renderValue) => [
  {
    key: "no",
    title: "NO",
    width: 60,
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    key: "bucketCode",
    title: "BUCKET CODE",
    dataIndex: "bucketCode",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "bucketName",
    title: "BUCKET NAME",
    dataIndex: "bucketName",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "itemCode",
    title: "ITEM CODE",
    dataIndex: "itemCode",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "itemName",
    title: "ITEM NAME",
    dataIndex: "itemName",
    isClassification:true,
    width: 200,
    render: renderValue,
  },
  {
    key: "billingType",
    title: "BILLING TYPE",
    dataIndex: "billingType",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "itemCategory",
    title: "ITEM CATEGORY",
    dataIndex: "itemCategory",
    width: 150,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "isLateCharge",
    title: "IS LATE CHARGE",
    dataIndex: "isLateCharge",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "sequence",
    title: "SEQUENCE",
    dataIndex: "sequence",
    width: 100,
    isNumber:true,
    render: renderValue,
  },
  {
    key: "currencyId",
    title: "CURRENCY ID",
    dataIndex: "currencyId",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
  {
    key: "itemPriority",
    title: "ITEM PRIORITY",
    dataIndex: "itemPriority",
    width: 120,
    isClassification:true,
    render: renderValue,
  },
];