import { hasValue, renderColumn, renderDateColumn } from "../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../utils/getColumnSearchProps";


export const columnsRating = (
  search,
  page = 0,
  pageSize = 0,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  // handleDetail = () => {}
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 60,
    render: (text, object, index) => index + 1,
  },
  {
    key: "calculationCode",
    title: "CALCULATION CODE",
    dataIndex: "calculationCode",
    isClassification: true,
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "calculationCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "calculationCode",
        hasValue(search["calculationCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "ratingCode",
    title: "RATING CODE",
    dataIndex: "ratingCode",
    isClassification: true,
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "ratingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "ratingCode",
        hasValue(search["ratingCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    isClassification: true,
    width: 130,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "currency",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "currency",
        hasValue(search["currency"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "timeUnit",
    title: "TIME UNIT",
    dataIndex: "timeUnit",
    width: 190,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "timeUnit",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "timeUnit",
        hasValue(search["timeUnit"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "billingCycle",
    title: "BILLING CYCLE",
    dataIndex: "billingCycle",
    width: 150,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingCycle",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "billingCycle",
        hasValue(search["billingCycle"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "periodName",
    title: "BILLING PERIOD",
    width: 160,
    sorter: true,
    isClassification: true,
    dataIndex: "periodName",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "periodName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "datePeriod",
    ),
    render: (text) =>
      renderDateColumn(
        "periodName",
        hasValue(search["periodName"]),
        searchText,
        text,
        "datePeriod",
        search,
      ),
  },
  {
    key: "transactionDate",
    title: "TRANSACTION DATE",
    width: 180,
    sorter: true,
    isClassification: true,
    dataIndex: "transactionDate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "transactionDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "transactionDate",
        hasValue(search["transactionDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "customerNumber",
        hasValue(search["customerNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 170,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "customerName",
        hasValue(search["customerName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 170,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountNumber",
        hasValue(search["accountNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 160,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountName",
        hasValue(search["accountName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "serviceType",
    title: "SERVICE TYPE",
    dataIndex: "serviceType",
    width: 150,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "serviceType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "serviceType",
        hasValue(search["serviceType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "sor",
    title: "SOR",
    dataIndex: "sor",
    width: 190,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "sor",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "sor",
        hasValue(search["sor"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    width: 150,
    dataIndex: "costCenter",
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "costCenter",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "costCenter",
        hasValue(search["costCenter"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountSegment",
    title: "ACCOUNT SEGMENT",
    dataIndex: "accountSegment",
    width: 180,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountSegment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountSegment",
        hasValue(search["accountSegment"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
    {
    key: "accountGroupType",
    title: "ACCOUNT GROUP TYPE",
    dataIndex: "accountGroupType",
    width: 210,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountGroupType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountGroupType",
        hasValue(search["accountGroupType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "meterReadingCode",
    title: "METER READING CODE",
    dataIndex: "meterReadingCode",
    width: 200,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "meterReadingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "meterReadingCode",
        hasValue(search["meterReadingCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "product",
    title: "PRODUCT",
    dataIndex: "product",
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "product",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "product",
        hasValue(search["product"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    title: "SERVICE AGREEMENT",
    children: [
      {
        key: "saType",
        title: "SA TYPE",
        dataIndex: "saType",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "saType",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "saType",
            hasValue(search["saType"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "paymentType",
        title: "PAYMENT TYPE",
        dataIndex: "paymentType",
        width: 130,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "paymentType",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "paymentType",
            hasValue(search["paymentType"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "saNumber",
        title: "SA NUMBER",
        dataIndex: "saNumber",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "saNumber",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "saNumber",
            hasValue(search["saNumber"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "minUsage",
        title: "MIN USAGE",
        dataIndex: "minUsage",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "minUsage",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "minUsage",
            hasValue(search["minUsage"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "maxUsage",
        title: "MAX USAGE",
        dataIndex: "maxUsage",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "maxUsage",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "maxUsage",
            hasValue(search["maxUsage"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "priceCode",
        title: "PRICE CODE",
        dataIndex: "priceCode",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceCode",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "priceCode",
            hasValue(search["priceCode"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "price",
        title: "PRICE",
        dataIndex: "price",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "price",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text,record) =>
          renderColumn(
            "price",
            hasValue(search["price"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.currency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
      {
        key: "uom",
        title: "UOM",
        dataIndex: "uom",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "uom",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "uom",
            hasValue(search["uom"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
    ],
  },
  {
    title: "CALCULATED USAGE PARTITION",
    children: [
      {
        key: "calculatedUsageMin",
        title: "MIN",
        dataIndex: "calculatedUsageMin",
        width: 120,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageMin",
            hasValue(search["calculatedUsageMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "calculatedUsageNormal",
        title: "NORMAL",
        dataIndex: "calculatedUsageNormal",
        width: 130,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageNormal",
            hasValue(search["calculatedUsageNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "calculatedUsageUop",
        title: "OUP",
        dataIndex: "calculatedUsageUop",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageUop",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageUop",
            hasValue(search["calculatedUsageUop"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "calculatedAdjustment",
        title: "ADJUSTMENT",
        dataIndex: "calculatedAdjustment",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedAdjustment",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedAdjustment",
            hasValue(search["calculatedAdjustment"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "calculatedTotal",
        title: "TOTAL CALCULATED",
        dataIndex: "calculatedTotal",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedTotal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedTotal",
            hasValue(search["calculatedTotal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.uom === "MMBTU" ? "energi" : "volume"
          ),
      },
    ],
  },
  {
    title: "CONVERTED CALCULATED USAGE PARTITION",
    children: [
      {
        key: "convertedCalculatedUom",
        title: "UOM",
        dataIndex: "convertedCalculatedUom",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedUom",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "convertedCalculatedUom",
            hasValue(search["convertedCalculatedUom"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "convertedCalculatedMin",
        title: "MIN",
        dataIndex: "convertedCalculatedMin",
        width: 130,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedMin",
            hasValue(search["convertedCalculatedMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "convertedCalculatedNormal",
        title: "NORMAL",
        dataIndex: "convertedCalculatedNormal",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedNormal",
            hasValue(search["convertedCalculatedNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "convertedCalculatedOup",
        title: "OUP",
        dataIndex: "convertedCalculatedOup",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedOup",
            hasValue(search["convertedCalculatedOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "convertedCalculatedAdjustment",
        title: "ADJUSMENT",
        dataIndex: "convertedCalculatedAdjustment",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedAdjustment",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedAdjustment",
            hasValue(search["convertedCalculatedAdjustment"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume"
          ),
      },
      {
        key: "convertedCalculatedTotal",
        title: "TOTAL CALCULATED",
        dataIndex: "convertedCalculatedTotal",
        width: 150,
        sorter: true,
        isNumber: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedTotal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedTotal",
            hasValue(search["convertedCalculatedTotal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume"
          ),
      },
    ],
  },
  {
    title: "AMOUNT PARTITION",
    children: [
      {
        key: "amountPartitionMin",
        title: "MIN",
        dataIndex: "amountPartitionMin",
        width: 150,
        sorter: true,
        isNumber : true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text,record) =>
          renderColumn(
            "amountPartitionMin",
            hasValue(search["amountPartitionMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.currency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
      {
        key: "amountPartitionNormal",
        title: "NORMAL",
        dataIndex: "amountPartitionNormal",
        width: 130,
        sorter: true,
        isNumber : true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "amountPartitionNormal",
            hasValue(search["amountPartitionNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.currency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
      {
        key: "amountPartitionOup",
        title: "OUP",
        dataIndex: "amountPartitionOup",
        width: 150,
        sorter: true,
        isNumber : true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text, record) =>
          renderColumn(
            "amountPartitionOup",
            hasValue(search["amountPartitionOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.currency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
    ],
  },
  {
    key: "amountPartition",
    title: "AMOUNT",
    width: 160,
    dataIndex: "amountPartition",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amountPartition",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text, record) =>
      renderColumn(
        "amountPartition",
        hasValue(search["amountPartition"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.currency === "USD" ? "currency-usd" : "currency-idr",
      ),
  },
  {
    key: "amountPartitionAdjustment",
    title: "TOTAL ADJUSTMENT",
    width: 160,
    dataIndex: "amountPartitionAdjustment",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amountPartitionAdjustment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text, record) =>
      renderColumn(
        "amountPartitionAdjustment",
        hasValue(search["amountPartitionAdjustment"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.currency === "USD" ? "currency-usd" : "currency-idr",
      ),
  },
  {
    key: "amountPartitionTotal",
    title: "TOTAL AMOUNT",
    width: 160,
    dataIndex: "amountPartitionTotal",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amountPartitionTotal",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text, record) =>
      renderColumn(
        "amountPartitionTotal",
        hasValue(search["amountPartitionTotal"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.currency === "USD" ? "currency-usd" : "currency-idr",
      ),
  },
];
