import { hasValue, renderColumn, renderDateColumn } from "../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../utils/getColumnSearchProps";

export const columnsRating = (
  search,
  page = 0,
  pageSize = 0,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  // handleDetail = () => {}
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 60,
    render: (text, object, index) => index + 1,
  },
  {
    key: "calculationCode",
    title: "CALCULATION CODE",
    dataIndex: "calculationCode",
    isClassification: true,
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "calculationCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "calculationCode",
        hasValue(search["calculationCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "ratingCode",
    title: "RATING CODE",
    dataIndex: "ratingCode",
    isClassification: true,
    width: 140,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "ratingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "ratingCode",
        hasValue(search["ratingCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "timeUnitContract",
    title: "CONTRACT TIME UNIT",
    dataIndex: "timeUnitContract",
    width: 190,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "timeUnitContract",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "timeUnitContract",
        hasValue(search["timeUnitContract"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "billingCycle",
    title: "BILLING CYCLE",
    dataIndex: "billingCycle",
    width: 170,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingCycle",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "billingCycle",
        hasValue(search["billingCycle"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "billingPeriod",
    title: "BILLING PERIOD",
    width: 160,
    sorter: true,
    isClassification: true,
    dataIndex: "billingPeriod",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "billingPeriod",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "datePeriod",
    ),
    render: (text) =>
      renderDateColumn(
        "billingPeriod",
        hasValue(search["billingPeriod"]),
        searchText,
        text,
        "datePeriod",
        search,
      ),
  },
  {
    key: "transactionDate",
    title: "TRANSACTION DATE",
    width: 190,
    sorter: true,
    isClassification: true,
    dataIndex: "transactionDate",
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "transactionDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "transactionDate",
        hasValue(search["transactionDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "customerNumber",
        hasValue(search["customerNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "customerName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "customerName",
        hasValue(search["customerName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountNumber",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountNumber",
        hasValue(search["accountNumber"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 160,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountName",
        hasValue(search["accountName"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accGroupType",
    title: "ACCOUNT GROUP TYPE",
    dataIndex: "accGroupType",
    width: 210,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accGroupType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accGroupType",
        hasValue(search["accGroupType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "serviceType",
    title: "SERVICE TYPE",
    dataIndex: "serviceType",
    width: 150,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "serviceType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "serviceType",
        hasValue(search["serviceType"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "sor",
    title: "SOR",
    dataIndex: "sor",
    width: 190,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "sor",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "sor",
        hasValue(search["sor"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    width: 150,
    dataIndex: "costCenter",
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "costCenter",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "costCenter",
        hasValue(search["costCenter"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "accountSegment",
    title: "ACCOUNT SEGMENT",
    dataIndex: "accountSegment",
    width: 180,
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "accountSegment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "accountSegment",
        hasValue(search["accountSegment"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "mreadingCode",
    title: "METER READING CODE",
    dataIndex: "mreadingCode",
    width: 200,
    isClassification: true,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "mreadingCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "mreadingCode",
        hasValue(search["mreadingCode"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "product",
    title: "PRODUCT",
    dataIndex: "product",
    sorter: true,
    isClassification: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "product",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "product",
        hasValue(search["product"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    title: "SERVICE AGREEMENT",
    children: [
      {
        key: "saType",
        title: "SA TYPE",
        dataIndex: "saType",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "saType",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "saType",
            hasValue(search["saType"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "paymentType",
        title: "PAYMENT TYPE",
        dataIndex: "paymentType",
        width: 130,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "paymentType",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "paymentType",
            hasValue(search["paymentType"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "sanumber",
        title: "SA NUMBER",
        dataIndex: "sanumber",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "sanumber",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "sanumber",
            hasValue(search["sanumber"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "minUsage",
        title: "MIN USAGE",
        dataIndex: "minUsage",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "minUsage",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "minUsage",
            hasValue(search["minUsage"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "maxUsage",
        title: "MAX USAGE",
        dataIndex: "maxUsage",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "maxUsage",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "maxUsage",
            hasValue(search["maxUsage"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "priceCode",
        title: "PRICE CODE",
        dataIndex: "priceCode",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceCode",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "priceCode",
            hasValue(search["priceCode"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "price",
        title: "PRICE",
        dataIndex: "price",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "price",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "price",
            hasValue(search["price"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "uom",
        title: "UOM",
        dataIndex: "uom",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "uom",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "uom",
            hasValue(search["uom"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
    ],
  },
  {
    title: "CALCULATED USAGE PARTITION",
    children: [
      {
        key: "minCalculated",
        title: "MIN",
        dataIndex: "minCalculated",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "minCalculated",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "minCalculated",
            hasValue(search["minCalculated"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "normalCalculated",
        title: "NOMRAL",
        dataIndex: "normalCalculated",
        width: 130,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "normalCalculated",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "normalCalculated",
            hasValue(search["normalCalculated"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "oupCalculated",
        title: "OUP",
        dataIndex: "oupCalculated",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "oupCalculated",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "oupCalculated",
            hasValue(search["oupCalculated"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "adjusmentCalculated",
        title: "ADJUSTMENT",
        dataIndex: "adjusmentCalculated",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "adjusmentCalculated",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "adjusmentCalculated",
            hasValue(search["adjusmentCalculated"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "totalCalculated",
        title: "TOTAL CALCULATED",
        dataIndex: "totalCalculated",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "totalCalculated",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "totalCalculated",
            hasValue(search["totalCalculated"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
    ],
  },
  {
    title: "CONVERTED CALCULATED USAGE PARTITION",
    children: [
      {
        key: "uomPartition",
        title: "UOM",
        dataIndex: "uomPartition",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "uomPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "uomPartition",
            hasValue(search["uomPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "minPartition",
        title: "MIN",
        dataIndex: "minPartition",
        width: 130,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "minPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "minPartition",
            hasValue(search["minPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "normalPartition",
        title: "NORMAL",
        dataIndex: "normalPartition",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "normalPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "normalPartition",
            hasValue(search["normalPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "oupPartition",
        title: "OUP",
        dataIndex: "oupPartition",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "oupPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "oupPartition",
            hasValue(search["oupPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "adjustmentPartition",
        title: "ADJUSMENT",
        dataIndex: "adjustmentPartition",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "adjustmentPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "adjustmentPartition",
            hasValue(search["adjustmentPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "totalCalculatedPartition",
        title: "TOTAL CALCULATED",
        dataIndex: "totalCalculatedPartition",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "totalCalculatedPartition",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "totalCalculatedPartition",
            hasValue(search["totalCalculatedPartition"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
    ],
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    isClassification: true,
    width: 130,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "currency",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "currency",
        hasValue(search["currency"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    title: "AMOUNT PARTITION",
    children: [
      {
        key: "minAmount",
        title: "MIN",
        dataIndex: "minAmount",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "minAmount",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "minAmount",
            hasValue(search["minAmount"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "normalAmount",
        title: "NORMAL",
        dataIndex: "normalAmount",
        width: 130,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "normalAmount",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "normalAmount",
            hasValue(search["normalAmount"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
      {
        key: "oupAmount",
        title: "OUP",
        dataIndex: "oupAmount",
        width: 150,
        sorter: true,
        isClassification: true,
        align: "center",
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "oupAmount",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
        ),
        render: (text) =>
          renderColumn(
            "oupAmount",
            hasValue(search["oupAmount"]),
            searchText,
            text,
            false,
            "input",
            search,
          ),
      },
    ],
  },
  {
    key: "amount",
    title: "AMOUNT",
    width: 160,
    dataIndex: "amount",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amount",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "amount",
        hasValue(search["amount"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
   {
    key: "totalAdjustment",
    title: "TOTAL ADJUSTMENT",
    width: 160,
    dataIndex: "totalAdjustment",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "totalAdjustment",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "totalAdjustment",
        hasValue(search["totalAdjustment"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
  {
    key: "totalAmount",
    title: "TOTAL AMOUNT",
    width: 160,
    dataIndex: "totalAmount",
    sorter: true,
    isNumber: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "totalAmount",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
    ),
    render: (text) =>
      renderColumn(
        "totalAmount",
        hasValue(search["totalAmount"]),
        searchText,
        text,
        false,
        "input",
        search,
      ),
  },
];
