import { RBI_ELEMENTS } from "./rbi_elements";
import { RBI_ROUTES } from "./rbi_routes";

export const rating_billing = [
  // prabilling
  {
    path: RBI_ROUTES.PRABILLING_VIEW,
    element: RBI_ELEMENTS.PRABILLING_VIEW_ELEMENTS,
  },
  {
    path: RBI_ROUTES.PRABILLING_CREATE,
    element: RBI_ELEMENTS.PRABILLING_CREATE_ELEMENTS,
  },
  {
    path: RBI_ROUTES.PRABILLING_VIEW_LOG,
    element: RBI_ELEMENTS.PRABILLOG_VIEW_ELEMENTS,
  },
  {
    path: RBI_ROUTES.PRABILLING_DETAIL,
    element: RBI_ELEMENTS.PRABILLING_DETAIL_ELEMENTS,
  },
  {
    path: RBI_ROUTES.PRABILLING_DETAIL_CUSTOMER,
    element: RBI_ELEMENTS.PRABILLCUS_DETAIL_ELEMENTS,
  },
  // calculation
  {
    path: RBI_ROUTES.CALCULATION_VIEW,
    element: RBI_ELEMENTS.CALCULATION_VIEW_ELEMENTS,
  },
  {
    path: RBI_ROUTES.CALCULATION_CREATE,
    element: RBI_ELEMENTS.CALCULATION_CREATE_ELEMENTS,
  },
  {
    path: RBI_ROUTES.CALCULATION_UPDATE,
    element: RBI_ELEMENTS.CALCULATION_UPDATE_ELEMENTS,
  },
  {
    path: RBI_ROUTES.CALCULATION_DETAIL,
    element: RBI_ELEMENTS.CALCULATION_DETAIL_ELEMENTS,
  },

  // billing
  {
    path: RBI_ROUTES.BILLING_VIEW,
    element: RBI_ELEMENTS.BILLING_VIEW_PAGE,
  },
  {
    path: RBI_ROUTES.BILLING_CREATE,
    element: RBI_ELEMENTS.BILLING_VIEW_PAGE,
  },

  // rating
  {
    path: RBI_ROUTES.RATING_VIEW,
    element: RBI_ELEMENTS.RATING_VIEW_PAGE,
  },
  // monitoring customer
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_VIEW,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_VIEW_ELEMENTS,
  },
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_PRA_BILLING_VS_RATING,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_PRA_BILLING_VS_RATING_ELEMENT,
  },
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_RATING_VS_BILLING,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_RATING_VS_BILLING_ELEMENT,
  },
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_DETAIL_PENDING_TRANSACTIONS,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_DETAIL_PENDING_TRANSACTIONS_ELEMENT,
  },
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_DETAIL_PENDING_APPROVALS,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_DETAIL_PENDING_APPROVALS_ELEMENT,
  },
  {
    path: RBI_ROUTES.MONITORING_CUSTOMER_DETAIL_GAP_PRA_BILLING_MASTER,
    element: RBI_ELEMENTS.MONITORING_CUSTOMER_DETAIL_GAP_PRA_BILLING_MASTER_ELEMENT,
  },

  // monitoring usage
  {
    path: RBI_ROUTES.MONITORING_USAGE_VIEW,
    element: RBI_ELEMENTS.MONITORING_USAGE_VIEW_ELEMENTS,
  },
  {
    path: RBI_ROUTES.MONITORING_USAGE_UPLOAD,
    element: RBI_ELEMENTS.MONITORING_USAGE_UPLOAD_ELEMENTS,
  },
  {
    path: RBI_ROUTES.MONITORING_USAGE_DETAIL,
    element: RBI_ELEMENTS.MONITORING_USAGE_DETAIL_ELEMENTS,
  },
  {
    path: RBI_ROUTES.MONITORING_USAGE_LIST_UPDATE,
    element: RBI_ELEMENTS.MONITORING_USAGE_UPDATE_ELEMENTS,
  },

  // adjustment billing
  {
    path: RBI_ROUTES.ADJUSTMENT_BILLING_VIEW,
    element: RBI_ELEMENTS.ADJUSTMENT_BILLING_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.ADJUSTMENT_BILLING_CREATE,
    element: RBI_ELEMENTS.ADJUSTMENT_BILLING_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.ADJUSTMENT_BILLING_UPDATE,
    element: RBI_ELEMENTS.ADJUSTMENT_BILLING_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.ADJUSTMENT_BILLING_DETAIL,
    element: RBI_ELEMENTS.ADJUSTMENT_BILLING_DETAIL_ELEMENT,
  },

  // POS
  {
    path: RBI_ROUTES.POS_VIEW,
    element: RBI_ELEMENTS.POS_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.POS_DETAIL,
    element: RBI_ELEMENTS.POS_DETAIL_ELEMENT,
  },
  {
    path: RBI_ROUTES.POS_CREATE,
    element: RBI_ELEMENTS.POS_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.POS_UPDATE,
    element: RBI_ELEMENTS.POS_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.POS_UPLOAD,
    element: RBI_ELEMENTS.POS_UPLOAD_ELEMENT,
  },

  // Master Data

  //Daily Rates
  {
    path: RBI_ROUTES.DAILY_RATE_VIEW,
    element: RBI_ELEMENTS.DAILY_RATE_VIEW,
  },
  {
    path: RBI_ROUTES.DAILY_RATE_CREATE,
    element: RBI_ELEMENTS.DAILY_RATE_CREATE,
  },
  {
    path: RBI_ROUTES.DAILY_RATE_UPDATE,
    element: RBI_ELEMENTS.DAILY_RATE_UPDATE,
  },
  {
    path: RBI_ROUTES.DAILY_RATE_DETAIL,
    element: RBI_ELEMENTS.DAILY_RATE_DETAIL,
  },
  {
    path: RBI_ROUTES.RATE_TYPE_CREATE,
    element: RBI_ELEMENTS.RATE_TYPE_CREATE,
  },
  {
    path: RBI_ROUTES.RATE_TYPE_UPDATE,
    element: RBI_ELEMENTS.RATE_TYPE_UPDATE,
  },

  //terms of payment
  {
    path: RBI_ROUTES.TERMS_OF_PAYMENT_VIEW,
    element: RBI_ELEMENTS.TERMS_OF_PAYMENT_VIEW,
  },
  {
    path: RBI_ROUTES.TERMS_OF_PAYMENT_CREATE,
    element: RBI_ELEMENTS.TERMS_OF_PAYMENT_CREATE,
  },
  {
    path: RBI_ROUTES.TERMS_OF_PAYMENT_UPDATE,
    element: RBI_ELEMENTS.TERMS_OF_PAYMENT_UPDATE,
  },
  {
    path: RBI_ROUTES.TERMS_OF_PAYMENT_DETAIL,
    element: RBI_ELEMENTS.TERMS_OF_PAYMENT_DETAIL,
  },

  // BILLING ITEM
  {
    path: RBI_ROUTES.BILLING_ITEM_VIEW,
    element: RBI_ELEMENTS.BILLING_ITEM_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_ITEM_DETAIL,
    element: RBI_ELEMENTS.BILLING_ITEM_DETAIL_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_ITEM_CREATE,
    element: RBI_ELEMENTS.BILLING_ITEM_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_ITEM_UPDATE,
    element: RBI_ELEMENTS.BILLING_ITEM_UPDATE_ELEMENT,
  },

  //Billing Cycle

  {
    path: RBI_ROUTES.BILLING_CYCLE_VIEW,
    element: RBI_ELEMENTS.BILLING_CYCLE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_CYCLE_DETAIL,
    element: RBI_ELEMENTS.BILLING_CYCLE_DETAIL_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_CYCLE_CREATE,
    element: RBI_ELEMENTS.BILLING_CYCLE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_CYCLE_UPDATE,
    element: RBI_ELEMENTS.BILLING_CYCLE_UPDATE_ELEMENT,
  },

  // Invoice Template
  {
    path: RBI_ROUTES.INVOICE_TEMPLATE_VIEW,
    element: RBI_ELEMENTS.INVOICE_TEMPLATE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.INVOICE_TEMPLATE_DETAIL,
    element: RBI_ELEMENTS.INVOICE_TEMPLATE_DETAIL_ELEMENT,
  },
  {
    path: RBI_ROUTES.INVOICE_TEMPLATE_CREATE,
    element: RBI_ELEMENTS.INVOICE_TEMPLATE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.INVOICE_TEMPLATE_UPDATE,
    element: RBI_ELEMENTS.INVOICE_TEMPLATE_UPDATE_ELEMENT,
  },

  //GENERAL TEMPLATE
  {
    path: RBI_ROUTES.GENEREAL_TEMPLATE_VIEW,
    element: RBI_ELEMENTS.GENERAL_TEMPLATE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.GENEREAL_TEMPLATE_DETAIL,
    element: RBI_ELEMENTS.GENERAL_TEMPLATE_DETAIL_ELEMENT,
  },
  {
    path: RBI_ROUTES.GENEREAL_TEMPLATE_CREATE,
    element: RBI_ELEMENTS.GENERAL_TEMPLATE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.GENEREAL_TEMPLATE_UPDATE,
    element: RBI_ELEMENTS.GENERAL_TEMPLATE_UPDATE_ELEMENT,
  },

  //BILLING BUCKET
  {
    path: RBI_ROUTES.BILLING_BUCKET_VIEW,
    element: RBI_ELEMENTS.BILLING_BUCKET_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_BUCKET_CREATE,
    element: RBI_ELEMENTS.BILLING_BUCKET_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_BUCKET_UPDATE,
    element: RBI_ELEMENTS.BILLING_BUCKET_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.BILLING_BUCKET_DETAIL,
    element: RBI_ELEMENTS.BILLING_BUCKET_DETAIL_ELEMENT,
  },

  //Tax Code
  {
    path: RBI_ROUTES.TAX_CODE_VIEW,
    element: RBI_ELEMENTS.TAX_CODE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.TAX_CODE_CREATE,
    element: RBI_ELEMENTS.TAX_CODE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.TAX_CODE_UPDATE,
    element: RBI_ELEMENTS.TAX_CODE_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.TAX_CODE_DETAIL,
    element: RBI_ELEMENTS.TAX_CODE_DETAIL_ELEMENT,
  },

  // Management Billing Installment
  {
    path: RBI_ROUTES.MANAGEMENT_BILLING_INSTALLMENT_VIEW,
    element: RBI_ELEMENTS.MANAGEMENT_BILLING_INSTALLMENT_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.MANAGEMENT_BILLING_INSTALLMENT_CREATE,
    element: RBI_ELEMENTS.MANAGEMENT_BILLING_INSTALLMENT_CREATE_ELEMENT,
  },

  // EFAKTUR CODE
  {
    path: RBI_ROUTES.EFAKTUR_CODE,
    element: RBI_ELEMENTS.EFAKTUR_CODE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.EFAKTUR_CODE_CREATE,
    element: RBI_ELEMENTS.EFAKTUR_CODE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.EFAKTUR_CODE_UPDATE,
    element: RBI_ELEMENTS.EFAKTUR_CODE_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.EFAKTUR_CODE_DETAIL,
    element: RBI_ELEMENTS.EFAKTUR_CODE_DETAIL_ELEMENT,
  },

  // signature digital
  {
    path: RBI_ROUTES.DIGITAL_SIGNATURE,
    element: RBI_ELEMENTS.DIGITAL_SIGNATURE_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.DIGITAL_SIGNATURE_CREATE,
    element: RBI_ELEMENTS.DIGITAL_SIGNATURE_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.DIGITAL_SIGNATURE_UPDATE,
    element: RBI_ELEMENTS.DIGITAL_SIGNATURE_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.DIGITAL_SIGNATURE_DETAIL,
    element: RBI_ELEMENTS.DIGITAL_SIGNATURE_DETAIL_ELEMENT,
  },
  // gl-account
  {
    path: RBI_ROUTES.GLACCOUNT,
    element: RBI_ELEMENTS.GLACCOUNT_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.GLACCOUNT_CREATE,
    element: RBI_ELEMENTS.GLACCOUNT_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.GLACCOUNT_UPDATE,
    element: RBI_ELEMENTS.GLACCOUNT_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.GLACCOUNT_DETAIL,
    element: RBI_ELEMENTS.GLACCOUNT_DETAIL_ELEMENT,
  },

  // Content Management
  {
    path: RBI_ROUTES.CONTENT_MANAGEMENT,
    element: RBI_ELEMENTS.CONTENT_MANAGEMENT_VIEW_ELEMENT,
  },
  {
    path: RBI_ROUTES.CONTENT_MANAGEMENT_CREATE,
    element: RBI_ELEMENTS.CONTENT_MANAGEMENT_CREATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.CONTENT_MANAGEMENT_UPDATE,
    element: RBI_ELEMENTS.CONTENT_MANAGEMENT_UPDATE_ELEMENT,
  },
  {
    path: RBI_ROUTES.CONTENT_MANAGEMENT_DETAIL,
    element: RBI_ELEMENTS.CONTENT_MANAGEMENT_DETAIL,
  },
];
