import { INVOICE_ELEMENTS } from "./invoice_elements";
import { INVOICE_ROUTES } from "./invoice_routes";

// invoice routes
export const invoice = [
  {
    path: INVOICE_ROUTES.GENERATE_INVOICE_VIEW,
    element: INVOICE_ELEMENTS.GENERATE_INVOICE_VIEW_PAGE,
  },
  {
    path: INVOICE_ROUTES.GENERATE_INVOICE_FORM,
    element: INVOICE_ELEMENTS.GENERATE_INVOICE_FORM_PAGE,
  },
  {
    path: INVOICE_ROUTES.PROFORMA_INVOICE_VIEW,
    element: INVOICE_ELEMENTS.PROFORMA_INVOICE_VIEW_PAGE,
  },
  {
    path: INVOICE_ROUTES.GENERATE_PROFORMA_INVOICE_FORM,
    element: INVOICE_ELEMENTS.GENERATE_PROFORMA_INVOICE_FORM_PAGE,
  },
  {
    path: INVOICE_ROUTES.E_METERAI_MANAGEMENT,
    element: INVOICE_ELEMENTS.E_METERAI_MANAGEMENT_PAGE,
  },
  {
    path: INVOICE_ROUTES.MANAGEMENT_DELIVERY_INVOICE,
    element: INVOICE_ELEMENTS.MANAGEMENT_DELIVERY_INVOICE_PAGE,
  },
  {
    path: INVOICE_ROUTES.CREATE_DELIVERY_JOB,
    element: INVOICE_ELEMENTS.CREATE_DELIVERY_JOB_PAGE,
  },
  {
    path: INVOICE_ROUTES.EFAKTUR_VIEW,
    element: INVOICE_ELEMENTS.EFAKTUR_VIEW_PAGE,
  },
  {
    path: INVOICE_ROUTES.EFAKTUR_VIEW_DETAIL,
    element: INVOICE_ELEMENTS.EFAKTUR_DETAIL_PAGE,
  },
  {
    path: INVOICE_ROUTES.ADJUSTMENT_INVOICE_VIEW,
    element: INVOICE_ELEMENTS.ADJUSTMENT_INVOICE_VIEW_PAGE,
  },
  {
    path: INVOICE_ROUTES.ADJUSTMENT_INVOICE_CREATE,
    element: INVOICE_ELEMENTS.ADJUSTMENT_INVOICE_FORM_PAGE,
  },
  {
    path: INVOICE_ROUTES.ADJUSTMENT_INVOICE_DETAIL,
    element: INVOICE_ELEMENTS.ADJUSTMENT_INVOICE_DETAIL_PAGE,
  },
];
