import Highlighter from "react-highlight-words";
import { Tooltip } from "antd";
import moment from "moment";
import { dateFormatting, renderColumn, toTitleCase } from "../../../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";
import StatusComponent from "../../../../../../components/StatusComponent";

export const columnWarranty = (
  page = 1,
  pageSize = 10,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  search = {}
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 60,
    align: "left",
    render: (text, object, index) => (page - 1) * pageSize + index + 1,
  },
  {
    key: "warrantyCode",
    title: "PAYMENT GUARANTEE CODE",
    dataIndex: "warrantyCode",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "warrantyCode", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "costCenter", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "accountNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "accountName", searchInput, searchedColumn, searchText, handleSearch),
  },
  // {
  //   key: "accountType",
  //   title: "ACCOUNT TYPE",
  //   dataIndex: "accountType",
  //   sorter: true,
  //   ...getColumnSearchPropsUseFilteredValue(search, "accountType", searchInput, searchedColumn, searchText, handleSearch),
  // },
  // {
  //   key: "saNumber",
  //   title: "SA NUMBER",
  //   dataIndex: "saNumber",
  //   sorter: true,
  //   ...getColumnSearchPropsPaging("saNumber", searchInput, searchedColumn, searchText, handleSearch),
  // },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "customerNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "customerName", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerSegment",
    title: "CUSTOMER SEGMENT",
    dataIndex: "customerSegment",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "customerSegment", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerGroup",
    title: "CUSTOMER GROUP",
    dataIndex: "customerGroup",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "customerGroup", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "warrantyType",
    title: "TYPE",
    dataIndex: "warrantyType",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "warrantyType", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "classificationType",
    title: "CLASSIFICATION TYPE",
    dataIndex: "classificationType",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "classificationType", searchInput, searchedColumn, searchText, handleSearch),
  },
  // {
  //   key: "warrantyType",
  //   title: "WARRANTY TYPE",
  //   dataIndex: "warrantyType",
  //   sorter: true,
  //   ...getColumnSearchPropsPaging("warrantyType", searchInput, searchedColumn, searchText, handleSearch),
  // },
  {
    key: "documentNumber",
    title: "DOCUMENT NUMBER",
    dataIndex: "documentNumber",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "documentNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "documentDate",
    title: "DOCUMENT DATE",
    dataIndex: "documentDate",
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "issuerBank",
    title: "ISSUER",
    dataIndex: "issuerBank",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "issuerBank", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "issuerBranch",
    title: "ISSUER BRANCH",
    dataIndex: "issuerBranch",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "issuerBranch", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    align: "center",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "currency", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currencyBalance",
    title: "BALANCE AMOUNT",
    dataIndex: "currencyBalance",
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "rateType",
    title: "RATE TYPE",
    dataIndex: "rateType",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "rateType", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "rateDate",
    title: "RATE DATE",
    dataIndex: "rateDate",
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "rate",
    title: "RATE",
    dataIndex: "rate",
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "equivalent",
    title: "EQV BALANCE AMOUNT",
    dataIndex: "equivalent",
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  // {
  //   key: "mutationDate",
  //   title: "MUTATION DATE",
  //   dataIndex: "mutationDate",
  //   sorter: true,
  //   render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  // },
  {
    key: "effectiveStartDate",
    title: "EFF. START DATE",
    dataIndex: "effectiveDate",
    sorter: true,
    align: "center",
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "effectiveEndDate",
    title: "EFF. END DATE",
    dataIndex: "endClaimDate",
    sorter: true,
    align: "center",
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "claimPeriod",
    title: "CLAIM PERIOD",
    dataIndex: "claimPeriod",
    sorter: true,
    render: (text, object) => object?.claimPeriodTermValue ? `${object?.claimPeriodTermValue} ${object?.claimPeriodTermType || ''}` : "-",
  },
  // {
  //   key: "effectiveDate",
  //   title: "EFFECTIVE DATE",
  //   dataIndex: "effectiveDate",
  //   sorter: true,
  //   render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  // },
  // {
  //   key: "expiringDate",
  //   title: "EXPIRING DATE",
  //   dataIndex: "expiringDate",
  //   sorter: true,
  //   render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  // },
  // {
  //   key: "endClaimDate",
  //   title: "END DATE CLAIM",
  //   dataIndex: "endClaimDate",
  //   sorter: true,
  //   render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  // },
  // {
  //   key: "claimPeriodTermType",
  //   title: "CLAIM TERM TYPE",
  //   dataIndex: "claimPeriodTermType",
  //   sorter: true,
  //   ...getColumnSearchPropsPaging("claimPeriodTermType", searchInput, searchedColumn, searchText, handleSearch),
  // },
  // {
  //   key: "claimPeriodTermValue",
  //   title: "CLAIM TERM VALUE",
  //   dataIndex: "claimPeriodTermValue",
  //   align: "right",
  //   sorter: true,
  // },
  {
    key: "description",
    title: "DESCRIPTION",
    dataIndex: "description",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(search, "description", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "status",
    title: "STATUS",
    dataIndex: "status",
    width: 120,
    fixed: "right",
    align: "center",
    render: (text) => renderColumn('status', searchedColumn, searchText, text, false, 'status', search)
  },
  {
    key: "approvalStatus",
    title: "STATUS APPROVAL",
    dataIndex: "approvalStatus",
    width: 190,
    align: "center",
    fixed: "right",
    render: (text) => renderColumn('approvalStatus', searchedColumn, searchText, text, false, 'status', search)
  },
];