import { PRODUCT_PROMO_ELEMENTS } from "./pp_elements";
import { PRODUCT_PROMO_ROUTES } from "./pp_routes";

export const product_promo = [
  // Product
  {
    path: PRODUCT_PROMO_ROUTES.VIEW_PRODUCT,
    element: PRODUCT_PROMO_ELEMENTS.VIEW_PRODUCT_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PRODUCT,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PRODUCT_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PRODUCT,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PRODUCT_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.DETAIL_PRODUCT,
    element: PRODUCT_PROMO_ELEMENTS.DETAIL_PRODUCT_PAGE,
  },

  // Pricing
  {
    path: PRODUCT_PROMO_ROUTES.VIEW_PRICING,
    element: PRODUCT_PROMO_ELEMENTS.VIEW_PRICING_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PRICING,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PRICING_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PRICING,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PRICING_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.DETAIL_PRICING,
    element: PRODUCT_PROMO_ELEMENTS.DETAIL_PRICING_PAGE,
  },

  // Pricing Adjustment
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PRICING_ADJUSTMENT,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PRICING_ADJUSTMENT_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PRICING_ADJUSTMENT,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PRICING_ADJUSTMENT_PAGE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.DETAIL_PRICING_ADJUSTMENT,
    element: PRODUCT_PROMO_ELEMENTS.DETAIL_PRICING_ADJUSTMENT_PAGE,
  },

  // Product Class
  {
    path: PRODUCT_PROMO_ROUTES.VIEW_PRODUCT_CLASS,
    element: PRODUCT_PROMO_ELEMENTS.VIEW_PRODUCT_CLASS,
  },
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PRODUCT_CLASS,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PRODUCT_CLASS,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PRODUCT_CLASS,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PRODUCT_CLASS,
  },

  // Pricing Rule
  {
    path: PRODUCT_PROMO_ROUTES.VIEW_PRICING_RULE,
    element: PRODUCT_PROMO_ELEMENTS.VIEW_PRICING_RULE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PRICING_RULE,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PRICING_RULE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PRICING_RULE,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PRICING_RULE,
  },
  {
    path: PRODUCT_PROMO_ROUTES.DETAIL_PRICING_RULE,
    element: PRODUCT_PROMO_ELEMENTS.DETAIL_PRICING_RULE,
  },

  // TOS
	{
		path: PRODUCT_PROMO_ROUTES.VIEW_TERM_OF_SERVICE,
		element: PRODUCT_PROMO_ELEMENTS.VIEW_TERM_OF_SERVICE,
	},
	{
		path: PRODUCT_PROMO_ROUTES.CREATE_TERM_OF_SERVICE,
		element: PRODUCT_PROMO_ELEMENTS.CREATE_TERM_OF_SERVICE,
	},
	{
		path: PRODUCT_PROMO_ROUTES.UPDATE_TERM_OF_SERVICE,
		element: PRODUCT_PROMO_ELEMENTS.UPDATE_TERM_OF_SERVICE,
	},
  
  // Promo Discount
  {
    path: PRODUCT_PROMO_ROUTES.VIEW_PROMO_DISCOUNT,
    element: PRODUCT_PROMO_ELEMENTS.VIEW_PROMO_DISCOUNT,
  },
  {
    path: PRODUCT_PROMO_ROUTES.CREATE_PROMO_DISCOUNT,
    element: PRODUCT_PROMO_ELEMENTS.CREATE_PROMO_DISCOUNT,
  },
  {
    path: PRODUCT_PROMO_ROUTES.UPDATE_PROMO_DISCOUNT,
    element: PRODUCT_PROMO_ELEMENTS.UPDATE_PROMO_DISCOUNT,
  },
  {
    path: PRODUCT_PROMO_ROUTES.DETAIL_PROMO_DISCOUNT,
    element: PRODUCT_PROMO_ELEMENTS.DETAIL_PROMO_DISCOUNT,
  },
];
