import { hasValue, renderColumn, renderDateColumn } from "../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../utils/getColumnSearchProps";
import StatusComponent from "../../../../components/StatusComponent";

export const columnsTaxExemption = (
  search,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
  handlePreview = () => {},
) => {
  return [
    {
      key: "no",
      title: "NO",
      isClassification: true,
      width: 60,
      render: (text, object, index) => index + 1,
    },
    {
      key: "proformaInvoiceNumber",
      title: "PROFORMA INVOICE NUMBER",
      dataIndex: "proformaInvoiceNumber",
      isClassification: true,
      width: 220,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "proformaInvoiceNumber",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "proformaInvoiceNumber",
          hasValue(search["proformaInvoiceNumber"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "proformaInvoice",
      title: "PROFORMA INVOICE",
      dataIndex: "proformaInvoice",
      isClassification: true,
      width: 250,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "proformaInvoice",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text, record) => {
        if (!text) return "-";
        return (
          <span
            style={{ color: "#0075BF", cursor: "pointer" }}
            onClick={() => handlePreview(record)}
          >
            {text}
          </span>
        );
      },
    },
    {
      key: "billingPeriod",
      title: "BILLING PERIOD",
      dataIndex: "billingPeriod",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "billingPeriod",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
        true,
        "datePeriod",
      ),
      render: (text) =>
        renderDateColumn(
          "billingPeriod",
          hasValue(search["billingPeriod"]),
          searchText,
          text,
          "datePeriod",
          search,
        ),
    },
    {
      key: "billingCode",
      title: "BILLING CODE",
      dataIndex: "billingCode",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "billingCode",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "billingCode",
          hasValue(search["billingCode"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "customerNumber",
      title: "CUSTOMER NUMBER",
      dataIndex: "customerNumber",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "customerNumber",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "customerNumber",
          hasValue(search["customerNumber"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "customerName",
      title: "CUSTOMER NAME",
      dataIndex: "customerName",
      isClassification: true,
      width: 250,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "customerName",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "customerName",
          hasValue(search["customerName"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountNumber",
      title: "ACCOUNT NUMBER",
      dataIndex: "accountNumber",
      isClassification: true,
      width: 200,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountNumber",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountNumber",
          hasValue(search["accountNumber"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountName",
      title: "ACCOUNT NAME",
      dataIndex: "accountName",
      isClassification: true,
      width: 250,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountName",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountName",
          hasValue(search["accountName"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "sor",
      title: "SOR",
      dataIndex: "sor",
      isClassification: true,
      width: 250,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "sor",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "sor",
          hasValue(search["sor"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "costCenter",
      title: "COST CENTER",
      dataIndex: "costCenter",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "costCenter",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "costCenter",
          hasValue(search["costCenter"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountSegment",
      title: "ACCOUNT SEGMENT",
      dataIndex: "accountSegment",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountSegment",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountSegment",
          hasValue(search["accountSegment"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountGroupType",
      title: "ACCOUNT GROUP TYPE",
      dataIndex: "accountGroupType",
      isClassification: true,
      width: 200,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountGroupType",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountGroupType",
          hasValue(search["accountGroupType"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "meterReadingCode",
      title: "METER READING CODE",
      dataIndex: "meterReadingCode",
      isClassification: true,
      width: 200,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "meterReadingCode",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "meterReadingCode",
          hasValue(search["meterReadingCode"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountType",
      title: "ACCOUNT TYPE",
      dataIndex: "accountType",
      isClassification: true,
      width: 160,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountType",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountType",
          hasValue(search["accountType"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "accountStatus",
      title: "ACCOUNT STATUS",
      dataIndex: "accountStatus",
      isClassification: true,
      width: 160,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "accountStatus",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "accountStatus",
          hasValue(search["accountStatus"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "customerManagement",
      title: "CUSTOMER MANAGEMENT",
      dataIndex: "customerManagement",
      isClassification: true,
      width: 220,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "customerManagement",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "customerManagement",
          hasValue(search["customerManagement"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "corporateCustomer",
      title: "CORPORATE CUSTOMER",
      dataIndex: "corporateCustomer",
      isClassification: true,
      width: 200,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "corporateCustomer",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "corporateCustomer",
          hasValue(search["corporateCustomer"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "classificationType",
      title: "CLASSIFICATION TYPE",
      dataIndex: "classificationType",
      isClassification: true,
      width: 200,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "classificationType",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "classificationType",
          hasValue(search["classificationType"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "serviceType",
      title: "SERVICE TYPE",
      dataIndex: "serviceType",
      isClassification: true,
      width: 160,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "serviceType",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "serviceType",
          hasValue(search["serviceType"]),
          searchText,
          text,
          false,
          "input",
          search,
        ),
    },
    {
      key: "billingAddress",
      title: "BILLING ADDRESS",
      dataIndex: "billAddress",
      isClassification: true,
      width: 250,
      sorter: true,
      ellipsis: {
        showTitle: false,
      },
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "billingAddress",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "billingAddress",
          hasValue(search["billingAddress"]),
          searchText,
          text,
          true,
          "input",
          search,
        ),
    },
    {
      key: "transactionDate",
      title: "TRANSACTION DATE",
      dataIndex: "transactionDate",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "transactionDate",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
        true,
        "date",
      ),
      render: (text) =>
        renderDateColumn(
          "transactionDate",
          hasValue(search["transactionDate"]),
          searchText,
          text,
          "date",
          search,
        ),
    },
    {
      key: "remark",
      title: "REMARK",
      dataIndex: "remark",
      width: 250,
      sorter: true,
      ellipsis: {
        showTitle: false,
      },
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "remark",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) =>
        renderColumn(
          "remark",
          hasValue(search["remark"]),
          searchText,
          text,
          true,
          "input",
          search,
        ),
    },
    {
      key: "statusBilling",
      title: "STATUS BILLING",
      dataIndex: "status",
      isClassification: true,
      width: 160,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "status",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) => <StatusComponent colour={text}>{text}</StatusComponent>,
    },
    {
      key: "statusExemption",
      title: "STATUS EXEMPTION",
      dataIndex: "statusApproval",
      isClassification: true,
      width: 180,
      sorter: true,
      ...getColumnSearchPropsUseFilteredValue(
        search,
        "statusApproval",
        searchInput,
        searchedColumn,
        searchText,
        handleSearch,
      ),
      render: (text) => <StatusComponent colour={text}>{text}</StatusComponent>,
    },
  ];
};
