import { JOB_MGMT_ROUTES } from "./job_routes";
import { JOB_MGMT_ELEMENTS } from "./job_elements";

export const job_management = [
  { path: JOB_MGMT_ROUTES.VIEW_JOB_SCHEDULER_MANAGEMENT, element: JOB_MGMT_ELEMENTS.VIEW_JOB_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB,                element: JOB_MGMT_ELEMENTS.VIEW_JOB_PAGE },
  { path: JOB_MGMT_ROUTES.CREATE_JOB,              element: JOB_MGMT_ELEMENTS.CREATE_JOB_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_DETAIL,         element: JOB_MGMT_ELEMENTS.VIEW_JOB_DETAIL_PAGE },
  { path: JOB_MGMT_ROUTES.UPDATE_JOB,              element: JOB_MGMT_ELEMENTS.UPDATE_JOB_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_GROUP,          element: JOB_MGMT_ELEMENTS.VIEW_JOB_GROUP_PAGE },
  { path: JOB_MGMT_ROUTES.CREATE_JOB_GROUP,        element: JOB_MGMT_ELEMENTS.CREATE_JOB_GROUP_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_GROUP_DETAIL,   element: JOB_MGMT_ELEMENTS.VIEW_JOB_GROUP_DETAIL_PAGE },
  { path: JOB_MGMT_ROUTES.UPDATE_JOB_GROUP,        element: JOB_MGMT_ELEMENTS.UPDATE_JOB_GROUP_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_EXECUTION,      element: JOB_MGMT_ELEMENTS.VIEW_JOB_EXECUTION_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_EXECUTION_DETAIL, element: JOB_MGMT_ELEMENTS.VIEW_JOB_EXECUTION_DETAIL_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_SCHEDULE,        element: JOB_MGMT_ELEMENTS.VIEW_JOB_SCHEDULE_PAGE },
  { path: JOB_MGMT_ROUTES.VIEW_JOB_SCHEDULE_DETAIL, element: JOB_MGMT_ELEMENTS.VIEW_JOB_SCHEDULE_DETAIL_PAGE },
];
