export const JOB_MGMT_ROUTES = {
  VIEW_JOB_SCHEDULER_MANAGEMENT: "/job-scheduler-management",
  VIEW_JOB:           "/job-scheduler-management/job-list",
  CREATE_JOB:         "/job-scheduler-management/job-list/create",
  VIEW_JOB_DETAIL:    "/job-scheduler-management/job-list/view",
  UPDATE_JOB:         "/job-scheduler-management/job-list/update",
  VIEW_JOB_GROUP:     "/job-scheduler-management/job-group-list",
  CREATE_JOB_GROUP:   "/job-scheduler-management/job-group-list/create",
  VIEW_JOB_GROUP_DETAIL: "/job-scheduler-management/job-group-list/view",
  UPDATE_JOB_GROUP:   "/job-scheduler-management/job-group-list/update",
  VIEW_JOB_EXECUTION: "/job-scheduler-management/job-execution-list",
  VIEW_JOB_EXECUTION_DETAIL: "/job-scheduler-management/job-execution-list/view",
  VIEW_JOB_SCHEDULE:        "/job-scheduler-management/job-scheduler-list",
  VIEW_JOB_SCHEDULE_DETAIL: "/job-scheduler-management/job-scheduler-list/view",
};
