#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: docker-hello-world
#  labels:
#    app: docker-hello-world
#spec:
#  selector:
#    matchLabels:
#      app: docker-hello-world
#  replicas: 3
#  template:
#    metadata:
#      labels:
#        app: docker-hello-world
#    spec:
#      containers:
#      - name: docker-hello-world
#        image: scottsbaldwin/docker-hello-world:latest
#        ports:
#        - containerPort: 80
#        resources:
#          requests:
#            cpu: 100m
#            memory: 128Mi
#          limits:
#            cpu: 250m
#            memory: 256Mi
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: docker-hello-world-service
#spec:
#  selector:
#    app: docker-hello-world
#  ports:
#    - port: 8088
#      targetPort: 80
#  type: ClusterIP
#
---
kind: Service
apiVersion: v1
metadata:
  name: dbs-module-mst
  namespace: billing-pgnbilling-staging
  labels:
    app.kubernetes.io/instance: dbs-module-mst
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dbs-module-mst
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: dbs-module-mst-0.1.0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8904
      targetPort: http
  selector:
    app.kubernetes.io/instance: dbs-module-mst
    app.kubernetes.io/name: dbs-module-mst
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: pgn-billing-stagging
#  labels:
#    app.kubernetes.io/instance: dbs-module-um
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/name: dbs-module-um
#    app.kubernetes.io/version: 1.0.0
#    helm.sh/chart: dbs-module-um-0.1.0
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/use-regex: 'true'
#spec:
#  ingressClassName: nginx
#  tls:
#  - hosts:
#      - stg-energy.pgn.co.id
#    secretName: tls-secret
#  rules:
#  - host: stg-energy.pgn.co.id
#    http:
#      paths:
#        - path: /um(/|$)(.*)
#          pathType: Prefix
#          backend:
#            service:
#              name: dbs-module-um
#              port:
#                number: 8903
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: cstor-pvc
#spec:
#  storageClassName: cstor-csi
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi