import React from "react";
import {
  hasValue,
  renderColumn,
  renderDateColumn,
} from "../../../../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../../utils/getColumnSearchProps";


export const columnsCalculationDetail = (
  page,
  pageSize,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch,
  search = {},
) => [
  {
    title: "No",
    dataIndex: "no",
    key: "no",
    width: 60,
    align: "center",
    render: (text, record, index) => (page - 1) * pageSize + index + 1,
  },
  {
    title: "Time Unit",
    dataIndex: "timeUnit",
    key: "timeUnit",
    isClassification: true,
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "timeUnit",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "timeUnit",
        hasValue(search["timeUnit"]),
        searchText,
        text || "",
        false,
        "input",
        search,
      ),
  },
  {
    title: "Transaction Date",
    dataIndex: "transactionDate",
    key: "transactionDate",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "transactionDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "date",
    ),
    render: (text) =>
      renderDateColumn(
        "transactionDate",
        hasValue(search["transactionDate"]),
        searchText,
        text,
        "date",
        search,
      ),
  },
  {
    title: "Usage",
    dataIndex: "usage",
    key: "usage",
    width: 150,
    align: "right",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "usage",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text, record) =>
      renderColumn(
        "usage",
        hasValue(search["usage"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
      ),
  },
  {
    title: "Min Usage",
    dataIndex: "minUsage",
    key: "minUsage",
    width: 150,
    align: "right",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "minUsage",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text, record) =>
      renderColumn(
        "minUsage",
        hasValue(search["minUsage"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
      ),
  },
  {
    title: "Max Usage",
    dataIndex: "maxUsage",
    key: "maxUsage",
    width: 150,
    align: "right",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "maxUsage",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text, record) =>
      renderColumn(
        "maxUsage",
        hasValue(search["maxUsage"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
      ),
  },
  {
    title: "SA Type",
    dataIndex: "saType",
    key: "saType",
    isClassification: true,
    width: 120,
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "saType",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "saType",
        hasValue(search["saType"]),
        searchText,
        text || "",
        false,
        "input",
        search,
      ),
  },
  // CALCULATED USAGE PARTITION
  {
    title: "CALCULATED USAGE PARTITION",
    children: [
      {
        title: "UOM",
        dataIndex: "calculatedUsageUom",
        key: "calculatedUsageUom",
        width: 120,
        align: "center",
        isClassification: true,
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageUom",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "calculatedUsageUom",
            hasValue(search["calculatedUsageUom"]),
            searchText,
            text || "",
            false,
            "input",
            search,
          ),
      },
      {
        title: "MIN",
        dataIndex: "calculatedUsageMin",
        key: "calculatedUsageMin",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageMin",
            hasValue(search["calculatedUsageMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
          ),
      },
      {
        title: "NORMAL",
        dataIndex: "calculatedUsageNormal",
        key: "calculatedUsageNormal",
        width: 150,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageNormal",
            hasValue(search["calculatedUsageNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
          ),
      },
      {
        title: "OUP",
        dataIndex: "calculatedUsageOup",
        key: "calculatedUsageOup",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "calculatedUsageOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "calculatedUsageOup",
            hasValue(search["calculatedUsageOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.calculatedUsageUom === "MMBTU" ? "energi" : "volume",
          ),
      },
    ],
  },
  //CONVERTED CALCULATED USAGE PARTITION
  {
    title: "CONVERTED CALCULATED USAGE PARTITION",
    children: [
      {
        title: "UOM",
        dataIndex: "convertedCalculatedUom",
        key: "convertedCalculatedUom",
        width: 120,
        align: "center",
        isClassification: true,
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedUom",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "convertedCalculatedUom",
            hasValue(search["convertedCalculatedUom"]),
            searchText,
            text || "",
            false,
            "input",
            search,
          ),
      },
      {
        title: "MIN",
        dataIndex: "convertedCalculatedMin",
        key: "convertedCalculatedMin",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedMin",
            hasValue(search["convertedCalculatedMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume",
          ),
      },
      {
        title: "NORMAL",
        dataIndex: "convertedCalculatedNormal",
        key: "convertedCalculatedNormal",
        width: 150,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedNormal",
            hasValue(search["convertedCalculatedNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume",
          ),
      },
      {
        title: "OUP",
        dataIndex: "convertedCalculatedOup",
        key: "convertedCalculatedOup",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "convertedCalculatedOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "convertedCalculatedOup",
            hasValue(search["convertedCalculatedOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.convertedCalculatedUom === "MMBTU" ? "energi" : "volume",
          ),
      },
    ],
  },
  // PRICE
  {
    title: "PRICE",
    children: [
      {
        title: "PRICE CODE",
        dataIndex: "priceCode",
        key: "priceCode",
        width: 150,
        align: "center",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceCode",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "priceCode",
            hasValue(search["priceCode"]),
            searchText,
            text || "",
            false,
            "input",
            search,
          ),
      },
      {
        title: "MIN",
        dataIndex: "priceMin",
        key: "priceMin",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "priceMin",
            hasValue(search["priceMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            "currency-idr",
          ),
      },
      {
        title: "NORMAL",
        dataIndex: "priceNormal",
        key: "priceNormal",
        width: 150,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "priceNormal",
            hasValue(search["priceNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            "currency-idr",
          ),
      },
      {
        title: "OUP",
        dataIndex: "priceOup",
        key: "priceOup",
        width: 130,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "priceOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "priceOup",
            hasValue(search["priceOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            "currency-idr",
          ),
      },
    ],
  },
  // AMOUNT PARTITION
  {
    title: "AMOUNT PARTITION",
    children: [
      {
        title: "CURRENCY",
        dataIndex: "amountPartitionCurrency",
        key: "amountPartitionCurrency",
        width: 120,
        isClassification: true,
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionCurrency",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text) =>
          renderColumn(
            "amountPartitionCurrency",
            hasValue(search["amountPartitionCurrency"]),
            searchText,
            text || "",
            false,
            "input",
            search,
          ),
      },
      {
        title: "MIN",
        dataIndex: "amountPartitionMin",
        key: "amountPartitionMin",
        width: 150,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionMin",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "amountPartitionMin",
            hasValue(search["amountPartitionMin"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.amountPartitionCurrency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
      {
        title: "NORMAL",
        dataIndex: "amountPartitionNormal",
        key: "amountPartitionNormal",
        width: 170,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionNormal",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "amountPartitionNormal",
            hasValue(search["amountPartitionNormal"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.amountPartitionCurrency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
      {
        title: "OUP",
        dataIndex: "amountPartitionOup",
        key: "amountPartitionOup",
        width: 150,
        isNumber: true,
        align: "right",
        sorter: true,
        ...getColumnSearchPropsUseFilteredValue(
          search,
          "amountPartitionOup",
          searchInput,
          searchedColumn,
          searchText,
          handleSearch,
          false,
          "input",
        ),
        render: (text, record) =>
          renderColumn(
            "amountPartitionOup",
            hasValue(search["amountPartitionOup"]),
            searchText,
            text,
            false,
            "input",
            search,
            record.amountPartitionCurrency === "USD" ? "currency-usd" : "currency-idr",
          ),
      },
    ],
  },
  {
    title: "Amount Partition",
    dataIndex: "amountPartition",
    key: "amountPartition",
    width: 160,
    isNumber: true,
    align: "right",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amountPartition",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text, record) =>
      renderColumn(
        "amountPartition",
        hasValue(search["amountPartition"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.amountPartitionCurrency === "USD" ? "currency-usd" : "currency-idr",
      ),
  },
  {
    title: "Amount Partition Total",
    dataIndex: "amountPartitionTotal",
    key: "amountPartitionTotal",
    width: 180,
    isNumber: true,
    align: "right",
    sorter: true,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "amountPartitionTotal",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text, record) =>
      renderColumn(
        "amountPartitionTotal",
        hasValue(search["amountPartitionTotal"]),
        searchText,
        text,
        false,
        "input",
        search,
        record.amountPartitionCurrency === "USD" ? "currency-usd" : "currency-idr",
      ),
  },
];