import {
  hasValue,
  renderColumn,
  renderDateColumn,
} from "../../../../../../utils";
import { getColumnSearchPropsUseFilteredValue } from "../../../../../../utils/getColumnSearchProps";

export const collectionTemplateColumns = (
  search,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {},
) => [
  {
    title: "NO",
    key: "no",
    width: 55,
    dataIndex: "key",
    align: "center",
    render: (text, object, index) => index + 1,
  },
  {
    title: "TEMPLATE CODE",
    dataIndex: "templateCode",
    key: "templateCode",
    width: 120,
    align: "left",
    sorter: true,
    filteredValue: search?.templateCode ? [search.templateCode] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "templateCode",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "templateCode",
        hasValue(search["templateCode"]),
        searchText,
        text,
        true,
        "input",
        search,
      ),
  },
  {
    title: "TEMPLATE NAME",
    dataIndex: "templateName",
    key: "templateName",
    width: 150,
    align: "left",
    sorter: true,
    filteredValue: search?.templateName ? [search.templateName] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "templateName",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "templateName",
        hasValue(search["templateName"]),
        searchText,
        text,
        true,
        "input",
        search,
      ),
  },
  {
    title: "START DATE",
    dataIndex: "startDate",
    key: "startDate",
    width: 110,
    sorter: true,
    align: "center",
    filteredValue: search?.startDate ? [search.startDate] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "startDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "date",
    ),
    render: (v) =>
      renderDateColumn(
        "startDate",
        hasValue(search["startDate"]),
        searchText,
        v,
        "date",
        search,
      ),
  },
  {
    title: "END DATE",
    dataIndex: "endDate",
    key: "endDate",
    width: 110,
    sorter: true,
    align: "center",
    filteredValue: search?.endDate ? [search.endDate] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "endDate",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "date",
    ),
    render: (v) =>
      renderDateColumn(
        "endDate",
        hasValue(search["endDate"]),
        searchText,
        v,
        "date",
        search,
      ),
  },
  {
    title: "DESCRIPTION",
    dataIndex: "description",
    key: "description",
    width: 160,
    sorter: true,
    ellipsis: { showTitle: false },
    filteredValue: search?.description ? [search.description] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "description",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      true,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "description",
        hasValue(search["description"]),
        searchText,
        text,
        true,
        "input",
        search,
      ),
  },
  {
    title: "STATUS",
    dataIndex: "status",
    key: "status",
    width: 90,
    sorter: true,
    filteredValue: search?.status ? [search.status] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "status",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "status",
        hasValue(search["status"]),
        searchText,
        text ? text.toUpperCase() : text,
        false,
        "status",
      ),
  },
  {
    title: "APPROVAL STATUS",
    dataIndex: "statusApproval",
    key: "statusApproval",
    width: 130,
    sorter: true,
    filteredValue: search?.statusApproval ? [search.statusApproval] : null,
    ...getColumnSearchPropsUseFilteredValue(
      search,
      "statusApproval",
      searchInput,
      searchedColumn,
      searchText,
      handleSearch,
      false,
      "input",
    ),
    render: (text) =>
      renderColumn(
        "statusApproval",
        hasValue(search["statusApproval"]),
        searchText,
        text ? text.toUpperCase() : text,
        false,
        "status",
      ),
  },
];
