export const getJobManagementColumns = () => [
  {
    title: "NO",
    key: "no",
    width: 60,
    align: "center",
    render: (_, __, index) => index + 1,
  },
  {
    title: "NAME",
    dataIndex: "name",
    key: "name",
    align: "left",
  },
  {
    title: "CODE",
    dataIndex: "code",
    key: "code",
    align: "left",
    width: 120,
  },
  {
    title: "TYPE",
    dataIndex: "type",
    key: "type",
    align: "left",
    width: 120,
  },
  {
    title: "DESC",
    dataIndex: "desc",
    key: "desc",
    align: "left",
    ellipsis: true,
  },
  {
    title: "PARAMETER",
    dataIndex: "parameter",
    key: "parameter",
    align: "left",
    ellipsis: true,
  },
  {
    title: "EXEC TYPE",
    dataIndex: "execType",
    key: "execType",
    align: "left",
    width: 120,
  },
  {
    title: "HANDLER CLASS",
    dataIndex: "handlerClass",
    key: "handlerClass",
    align: "left",
    ellipsis: true,
  },
  {
    title: "TIMEOUT",
    dataIndex: "timeout",
    key: "timeout",
    align: "center",
    width: 100,
  },
  {
    title: "MAX RETRY",
    dataIndex: "maxRetry",
    key: "maxRetry",
    align: "center",
    width: 100,
  },
  {
    title: "CREATED BY",
    dataIndex: "createdBy",
    key: "createdBy",
    align: "left",
    width: 140,
  },
  {
    title: "CREATED DATE",
    dataIndex: "createdDate",
    key: "createdDate",
    align: "left",
    width: 140,
  },
  {
    title: "UPDATED BY",
    dataIndex: "updatedBy",
    key: "updatedBy",
    align: "left",
    width: 140,
  },
  {
    title: "UPDATED DATE",
    dataIndex: "updatedDate",
    key: "updatedDate",
    align: "left",
    width: 140,
  },
  {
    title: "MODULE",
    dataIndex: "module",
    key: "module",
    align: "left",
    width: 120,
  },
  {
    title: "ACCESS GROUP",
    dataIndex: "accessGroup",
    key: "accessGroup",
    align: "left",
    width: 140,
  },
  {
    title: "PARENT",
    dataIndex: "parent",
    key: "parent",
    align: "left",
    width: 120,
  },
];
