import { RELATIONSHIP_ROUTES } from "./relationship_routes";
import { RELATIONSHIP_ELEMENTS } from "./relationship_elements";

export const relationship = [
  { path: RELATIONSHIP_ROUTES.VIEW_RELATIONSHIP,   element: RELATIONSHIP_ELEMENTS.VIEW_RELATIONSHIP_PAGE },
  { path: RELATIONSHIP_ROUTES.CREATE_RELATIONSHIP, element: RELATIONSHIP_ELEMENTS.CREATE_RELATIONSHIP_PAGE },
  { path: RELATIONSHIP_ROUTES.UPDATE_RELATIONSHIP, element: RELATIONSHIP_ELEMENTS.UPDATE_RELATIONSHIP_PAGE },
  { path: RELATIONSHIP_ROUTES.DETAIL_RELATIONSHIP, element: RELATIONSHIP_ELEMENTS.DETAIL_RELATIONSHIP_PAGE },
];
