import { SYSTEM_SETUP_ELEMENTS } from "./setup_elements";
import { SYSTEM_SETUP_ROUTES } from "./setup_routes";

export const system_setup = [
  // ACTION
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_ACTION,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_ACTION_PAGE,
    authority: "20",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_ACTION,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_ACTION_PAGE,
    authority: "21",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_ACTION,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_ACTION_PAGE,
    authority: "22",
  },

  // ENTITY
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_ENTITY,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_ENTITY_PAGE,
    authority: "30",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_ENTITY,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_ENTITY_PAGE,
    authority: "31",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_ENTITY,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_ENTITY_PAGE,
    authority: "32",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_ENTITY,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_ENTITY_PAGE,
    authority: "33",
  },

  // COST CENTER
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_COST_CENTER,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_COST_CENTER_PAGE,
    authority: "40",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_COST_CENTER,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_COST_CENTER_PAGE,
    authority: "41",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_COST_CENTER,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_COST_CENTER_PAGE,
    authority: "42",
  },

  // GROUP ACCESS
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_GROUP_ACCESS,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_GROUP_ACCESS_PAGE,
    authority: "50",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_GROUP_ACCESS,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_GROUP_ACCESS_PAGE,
    authority: "51",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_GROUP_ACCESS,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_GROUP_ACCESS_PAGE,
    authority: "53",
  },

  // ANNOUNCEMENT
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_ANNOUNCEMENT,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_ANNOUNCEMENT_PAGE,
    authority: "60",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_ANNOUNCEMENT,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_ANNOUNCEMENT_PAGE,
    authority: "61",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_ANNOUNCEMENT,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_ANNOUNCEMENT_PAGE,
    authority: "62",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_ANNOUNCEMENT,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_ANNOUNCEMENT_PAGE,
    authority: "63",
  },

  // JOB
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_JOB,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_JOB_PAGE,
    authority: "70",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_JOB,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_JOB_PAGE,
    authority: "71",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_JOB,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_JOB_PAGE,
    authority: "72",
  },

  // MENU
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_MENU,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_MENU_PAGE,
    authority: "80",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_MENU,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_MENU_PAGE,
    authority: "81",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_MENU,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_MENU_PAGE,
    authority: "82",
  },
  // global type
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_GLOBAL_TYPE,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_GLOBAL_PAGE,
    authority: "90",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_GLOBAL_TYPE,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_GLOBAL_PAGE,
    authority: "91",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_GLOBAL_TYPE,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_GLOBAL_PAGE,
    authority: "92",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_GLOBAL_TYPE,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_GLOBAL_PAGE,
    authority: "93",
  },

  // GLOBAL PROPERTIES
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_GLOBAL_PROPERTIES,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_GLOBAL_PROPERTIES_PAGE,
    authority: "100",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_GLOBAL_PROPERTIES,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_GLOBAL_PROPERTIES_PAGE,
    authority: "101",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_GLOBAL_PROPERTIES,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_GLOBAL_PROPERTIES_PAGE,
    authority: "102",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_GLOBAL_PROPERTIES,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_GLOBAL_PROPERTIES_PAGE,
    authority: "103",
  },

  // POSITION MASTER DATA
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_MASTER_POSITION,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_MASTER_POSITION_PAGE,
    authority: "110",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_MASTER_POSITION,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_MASTER_POSITION_PAGE,
    authority: "111",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_MASTER_POSITION,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_MASTER_POSITION_PAGE,
    authority: "112",
  },

  // Login Background
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_LOGIN_BACKGROUND,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_LOGIN_BACKGROUND_PAGE,
    authority: "120",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_LOGIN_BACKGROUND,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_LOGIN_BACKGROUND_PAGE,
    authority: "121",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_LOGIN_BACKGROUND,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_LOGIN_BACKGROUND_PAGE,
    authority: "122",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_LOGIN_BACKGROUND,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_LOGIN_BACKGROUND_PAGE,
    authority: "123",
  },

  // // POSITION MASTER DATA
  // {
  // 	path: SYSTEM_SETUP_ROUTES.VIEW_MASTER_POSITION,
  // 	element: SYSTEM_SETUP_ELEMENTS.VIEW_MASTER_POSITION_PAGE,
  // 	authority: "110"
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.CREATE_MASTER_POSITION,
  // 	element: SYSTEM_SETUP_ELEMENTS.CREATE_MASTER_POSITION_PAGE,
  // 	authority: "111"
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.UPDATE_MASTER_POSITION,
  // 	element: SYSTEM_SETUP_ELEMENTS.UPDATE_MASTER_POSITION_PAGE,
  // 	authority: "112"
  // },

  // // Login Background
  // {
  // 	path: SYSTEM_SETUP_ROUTES.VIEW_LOGIN_BACKGROUND,
  // 	element: SYSTEM_SETUP_ELEMENTS.VIEW_LOGIN_BACKGROUND_PAGE,
  // 	authority:"120"
  // },
  // {
  // 	path:SYSTEM_SETUP_ROUTES.CREATE_LOGIN_BACKGROUND,
  // 	element: SYSTEM_SETUP_ELEMENTS.CREATE_LOGIN_BACKGROUND_PAGE,
  // 	authority: "121"
  // },
  // {
  // 	path:SYSTEM_SETUP_ROUTES.UPDATE_LOGIN_BACKGROUND,
  // 	element: SYSTEM_SETUP_ELEMENTS.CREATE_LOGIN_BACKGROUND_PAGE,
  // 	authority: "122"
  // },
  // {
  // 	path:SYSTEM_SETUP_ROUTES.DETAIL_LOGIN_BACKGROUND,
  // 	element: SYSTEM_SETUP_ELEMENTS.DETAIL_LOGIN_BACKGROUND_PAGE,
  // 	authority: "123"
  // },

  // // ASSETS
  // {
  // 	path: SYSTEM_SETUP_ROUTES.VIEW_MASTER_ASSETS,
  // 	element: SYSTEM_SETUP_ELEMENTS.VIEW_MASTER_ASSETS_PAGE
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.CREATE_MASTER_ASSETS,
  // 	element: SYSTEM_SETUP_ELEMENTS.CREATE_MASTER_ASSETS_PAGE
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.UPDATE_MASTER_ASSETS,
  // 	element: SYSTEM_SETUP_ELEMENTS.UPDATE_MASTER_ASSETS_PAGE
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.DETAIL_MASTER_ASSETS,
  // 	element: SYSTEM_SETUP_ELEMENTS.DETAIL_MASTER_ASSETS_PAGE
  // },
  // {
  // 	path: SYSTEM_SETUP_ROUTES.UPLOAD_MASTER_ASSETS,
  // 	element: SYSTEM_SETUP_ELEMENTS.UPLOAD_MASTER_ASSETS_PAGE
  // },

  // // MAINTENANCE MODES
  // {
  // 	path:SYSTEM_SETUP_ROUTES.VIEW_MAINTENANCE_MODE,
  // 	element: SYSTEM_SETUP_ELEMENTS.VIEW_MAINTENANCE_MODE,
  // },
  // {
  // 	path:SYSTEM_SETUP_ROUTES.DETAIL_MAINTENANCE_MODE,
  // 	element: SYSTEM_SETUP_ELEMENTS.DETAIL_MAINTENANCE_MODE,
  // },
  // ASSETS
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_MASTER_ASSETS,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_MASTER_ASSETS_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_MASTER_ASSETS,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_MASTER_ASSETS_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_MASTER_ASSETS,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_MASTER_ASSETS_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_MASTER_ASSETS,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_MASTER_ASSETS_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPLOAD_MASTER_ASSETS,
    element: SYSTEM_SETUP_ELEMENTS.UPLOAD_MASTER_ASSETS_PAGE,
  },

  // MAINTENANCE MODES
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_MAINTENANCE_MODE,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_MAINTENANCE_MODE,
    authority: "130",
  },
  // PAYMENT CYCLE
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_PAYMENT_CYCLE,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_PAYMENT_CYCLE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_PAYMENT_CYCLE,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_PAYMENT_CYCLE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_PAYMENT_CYCLE,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_PAYMENT_CYCLE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_PAYMENT_CYCLE,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_PAYMENT_CYCLE,
  },
  // PAYMENT PERIOD
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_PAYMENT_PERIOD,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_PAYMENT_PERIOD,
    authority: "53",
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_PAYMENT_PERIOD,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_PAYMENT_PERIOD,
    authority: "53",
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_PAYMENT_PERIOD,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_PAYMENT_PERIOD,
    authority: "53",
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_PAYMENT_PERIOD,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_PAYMENT_PERIOD,
    authority: "53",
  },
  // BILLING ITEM CATEGORY
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_BILLING_ITEM_CATEGORY,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_BILLING_ITEM_CATEGORY,
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_BILLING_ITEM_CATEGORY,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_BILLING_ITEM_CATEGORY,
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_BILLING_ITEM_CATEGORY,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_BILLING_ITEM_CATEGORY,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_BILLING_ITEM_CATEGORY,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_BILLING_ITEM_CATEGORY,
  },

  // CALENDAR
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_CALENDAR,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_CALENDAR_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_CALENDAR,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_CALENDAR_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_CALENDAR,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_CALENDAR_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_CALENDAR,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_CALENDAR_PAGE,
  },

  // PRE-REQUISITE TEMPLATE
  {
    path: SYSTEM_SETUP_ROUTES.VIEW_PRE_REQUISITE_TEMPLATE,
    element: SYSTEM_SETUP_ELEMENTS.VIEW_PRE_REQUISITE_TEMPLATE_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.DETAIL_PRE_REQUISITE_TEMPLATE,
    element: SYSTEM_SETUP_ELEMENTS.DETAIL_PRE_REQUISITE_TEMPLATE_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.CREATE_PRE_REQUISITE_TEMPLATE,
    element: SYSTEM_SETUP_ELEMENTS.CREATE_PRE_REQUISITE_TEMPLATE_PAGE,
  },
  {
    path: SYSTEM_SETUP_ROUTES.UPDATE_PRE_REQUISITE_TEMPLATE,
    element: SYSTEM_SETUP_ELEMENTS.UPDATE_PRE_REQUISITE_TEMPLATE_PAGE,
  },
];
