import { DEBT_AND_COLLECTION_ROUTES } from "./rc_routes";
import { DEBT_AND_COLLECTION_ELEMENTS } from "./rc_elements";

export const debt_and_collection = [
  // Grace Period
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_GRACE_PERIOD_PAGE,
  },

  // Activity Name
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_ACTIVITY_NAME,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_ACTIVITY_NAME_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_ACTIVITY_NAME,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_ACTIVITY_NAME_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_ACTIVITY_NAME,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_ACTIVITY_NAME_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_ACTIVITY_NAME,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_ACTIVITY_NAME_PAGE,
  },

  // Template Reminding
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_TEMPLATE_REMINDING,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_TEMPLATE_REMINDING_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_TEMPLATE_REMINDING,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_TEMPLATE_REMINDING_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_TEMPLATE_REMINDING,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_TEMPLATE_REMINDING_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_TEMPLATE_REMINDING,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_TEMPLATE_REMINDING_PAGE,
  },

  // Activity Type
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_ACTIVITY_TYPE,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_ACTIVITY_TYPE_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_ACTIVITY_TYPE,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_ACTIVITY_TYPE_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_ACTIVITY_TYPE,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_ACTIVITY_TYPE_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_ACTIVITY_TYPE,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_ACTIVITY_TYPE_PAGE,
  },

  // Activity Action
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_ACTIVITY_ACTION,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_ACTIVITY_ACTION_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_ACTIVITY_ACTION,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_ACTIVITY_ACTION_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_ACTIVITY_ACTION,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_ACTIVITY_ACTION_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_ACTIVITY_ACTION,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_ACTIVITY_ACTION_PAGE,
  },


  // Activities
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_ACTIVITIES,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_ACTIVITIES_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_ACTIVITIES,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_ACTIVITIES_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_ACTIVITIES,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_ACTIVITIES_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_ACTIVITIES,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_ACTIVITIES_PAGE,
  },


  // Plan Activities
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_ACTIVITIES_PLAN,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_ACTIVITIES_PLAN_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_ACTIVITIES_PLAN,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_ACTIVITIES_PLAN_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_ACTIVITIES_PLAN,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_ACTIVITIES_PLAN_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_ACTIVITIES_PLAN,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_ACTIVITIES_PLAN_PAGE,
  },
];
