import { DEBT_AND_COLLECTION_ROUTES } from "./rc_routes";
import { DEBT_AND_COLLECTION_ELEMENTS } from "./rc_elements";

export const debt_and_collection = [
  // Grace Period
  {
    path: DEBT_AND_COLLECTION_ROUTES.VIEW_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.VIEW_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.DETAIL_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.DETAIL_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.CREATE_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.CREATE_GRACE_PERIOD_PAGE,
  },
  {
    path: DEBT_AND_COLLECTION_ROUTES.UPDATE_GRACE_PERIOD,
    element: DEBT_AND_COLLECTION_ELEMENTS.UPDATE_GRACE_PERIOD_PAGE,
  },
];
