import Highlighter from "react-highlight-words";
import { Tooltip } from "antd";
import moment from "moment";
import { dateFormatting } from "../../../../../../../utils";
import { getColumnSearchPropsPaging } from "../../../../../../../utils/getColumnSearchProps";
import StatusComponent from "../../../../../../../components/StatusComponent";

export const columnsWarrantyInfo = (
  page = 1,
  pageSize = 10,
  searchInput,
  searchedColumn,
  searchText,
  handleSearch = () => {}
) => [
  {
    key: "no",
    title: "NO",
    isClassification: true,
    width: 60,
    render: (text, object, index) => (page - 1) * pageSize + index + 1,
  },
  {
    key: "warrantyCode",
    title: "PAYMENT GUARANTEE",
    dataIndex: "warrantyCode",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("warrantyCode", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "costCenter",
    title: "COST CENTER",
    dataIndex: "costCenter",
    width: 180,
    sorter: true,
    ...getColumnSearchPropsPaging("costCenter", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountNumber",
    title: "ACCOUNT NUMBER",
    dataIndex: "accountNumber",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsPaging("accountNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "accountName",
    title: "ACCOUNT NAME",
    dataIndex: "accountName",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("accountName", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerNumber",
    title: "CUSTOMER NUMBER",
    dataIndex: "customerNumber",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsPaging("customerNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerName",
    title: "CUSTOMER NAME",
    dataIndex: "customerName",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("customerName", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerSegment",
    title: "CUSTOMER SEGMENT",
    dataIndex: "customerSegment",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("customerSegment", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "customerGroup",
    title: "CUSTOMER GROUP",
    dataIndex: "customerGroup",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("customerGroup", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "type",
    title: "TYPE",
    dataIndex: "type",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsPaging("type", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "issuerBank",
    title: "ISSUER",
    dataIndex: "issuerBank",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsPaging("issuerBank", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "issuerBranch",
    title: "ISSUER BRANCH",
    dataIndex: "issuerBranch",
    width: 150,
    sorter: true,
    ...getColumnSearchPropsPaging("issuerBranch", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currency",
    title: "CURRENCY",
    dataIndex: "currency",
    width: 120,
    sorter: true,
    ...getColumnSearchPropsPaging("currency", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "currencyBalance",
    title: "BALANCE",
    dataIndex: "currencyBalance",
    width: 150,
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "rate",
    title: "RATE",
    dataIndex: "rate",
    width: 150,
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "rateDate",
    title: "RATE DATE",
    dataIndex: "rateDate",
    width: 150,
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "equivalent",
    title: "EQV. BALANCE",
    dataIndex: "equivalent",
    width: 150,
    align: "right",
    sorter: true,
    render: (text) => text?.toLocaleString(),
  },
  {
    key: "documentNumber",
    title: "DOCUMENT NUMBER",
    dataIndex: "documentNumber",
    width: 200,
    sorter: true,
    ...getColumnSearchPropsPaging("documentNumber", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "mutationDate",
    title: "MUTATION DATE",
    dataIndex: "mutationDate",
    width: 150,
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "effectiveDate",
    title: "EFFECTIVE DATE",
    dataIndex: "effectiveDate",
    width: 150,
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "expiringDate",
    title: "EXPIRING DATE",
    dataIndex: "expiringDate",
    width: 150,
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "endClaimDate",
    title: "END DATE CLAIM",
    dataIndex: "endClaimDate",
    width: 150,
    sorter: true,
    render: (text) => (text ? moment(text).format(dateFormatting.dateCapital) : ""),
  },
  {
    key: "description",
    title: "DESCRIPTION",
    dataIndex: "description",
    width: 250,
    sorter: true,
    ...getColumnSearchPropsPaging("description", searchInput, searchedColumn, searchText, handleSearch),
  },
  {
    key: "status",
    title: "STATUS",
    dataIndex: "status",
    width: 120,
    align: "center",
    render: (text) => (
      <div className="flex justify-center">
        <StatusComponent colour={text}>{text}</StatusComponent>
      </div>
    ),
  },
  {
    key: "approvalStatus",
    title: "STATUS APPROVAL",
    dataIndex: "approvalStatus",
    width: 150,
    align: "center",
    render: (text) => (
      <div className="flex justify-center">
        <StatusComponent colour={text}>{text}</StatusComponent>
      </div>
    ),
  },
];