name: Deploy to AKS with Kubeconfig
on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on:
      group: Development
      labels:
        - self-hosted
        - Linux
        - Development
        - X64
    environment: development
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build React Application
      run: |
        docker run --rm \
          -v "$(pwd):/app" \
          -v "/app/node_modules" \
          -w /app \
          node:22.11.0 \
          sh -c "npm install -g npm@10.9.0 && npm install --force && npm run build"

    - name: Packaging React To Docker Image and Push to Registry
      run: |
        DOCKER_TAG="${{ vars.IMAGE_NAME }}:1.0.0-alpha"
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ vars.REGISTRY_URL }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        docker build -t "${DOCKER_TAG}" .
        docker push "${DOCKER_TAG}"

    - name: Set up kubeconfig to access cluster
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl config view

    - name: Test Kubernetes connectivity
      run: |
        kubectl get pods -n ${{ vars.KUBE_NAMESPACE }}

    - name: Registry Authentication
      run: |
        helm registry login registry.pgn.co.id \
          -u ${{ secrets.REGISTRY_USERNAME }} \
          -p ${{ secrets.REGISTRY_PASSWORD }}

    # HELM_CATALOG_APP="oci://registry.pgn.co.id/energy/helm/pgn-frontend"
    # HELM_NAME="pgn-frontend"
    - name: Push helm
      run: |
        HELM_CATALOG_APP="${{ vars.HELM_CATALOG_APP }}"
        HELM_NAME="${{ vars.HELM_NAME }}"
        helm package "${HELM_CATALOG_APP}"
        PREPARED_HELM_TO_PUSH="${{ vars.HELM_CATALOG_APP }}-0.1.0.tgz"
        helm push "./${PREPARED_HELM_TO_PUSH}" "${HELM_NAME}"

    # HELM_CHART_PATH="oci://registry.pgn.co.id/energy/helm/pgn-frontend/pgn-frontend" --trigger
    # HELM_NAME="pgn-frontend"
    - name: Deploy Kubernetes manifests
      run: |
        HELM_CHART_PATH="${{ vars.HELM_NAME }}/${{ vars.HELM_CATALOG_APP }}"
        HELM_CATALOG_APP="${{ vars.HELM_CATALOG_APP }}"
        helm upgrade --install "${HELM_CATALOG_APP}" "${HELM_CHART_PATH}" --version 0.1.0 \
          --namespace=energy-development \
          --set resources.limits.cpu="${{ vars.CPU_LIMIT }}" \
          --set resources.limits.memory="${{ vars.MEMORY_LIMIT }}" \
          --set resources.requests.cpu="${{ vars.CPU_REQUEST }}" \
          --set resources.requests.memory="${{ vars.MEMORY_REQUEST }}" \
          --set serviceAccount.name="${{ vars.VAULT_SERVICE_ACCOUNT }}" \
          --set podAnnotations.vault.authPath="auth/energy-development-kubernetes" \
          --set podAnnotations.vault.secretPath=${{ vars.VAULT_CONFIG_PATH }} \
          --set imagePullSecrets.name=${{ vars.IMAGE_PULL_SECRET }} \
          --set podAnnotations.releaseNamespace=${{ vars.KUBE_NAMESPACE }} \
          --set image.name=${{ vars.IMAGE_NAME }} \
          --set image.tag="1.0.0-alpha" \
          --set podAnnotations.vault.role=${{ vars.VAULT_ROLE }}