import { WORK_ORDER_ROUTES } from "./work_order_routes";
import { WORK_ORDER_ELEMENTS } from "./work_order_elements";

export const work_order = [
  // Standalone WO
  { path: WORK_ORDER_ROUTES.WO_LIST, element: WORK_ORDER_ELEMENTS.WO_LIST_PAGE },
  { path: WORK_ORDER_ROUTES.WO_CREATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },
  { path: WORK_ORDER_ROUTES.WO_VIEW, element: WORK_ORDER_ELEMENTS.WO_DETAIL_PAGE },
  { path: WORK_ORDER_ROUTES.WO_UPDATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },

  // WO Under Account
  { path: WORK_ORDER_ROUTES.ACCOUNT_WO_LIST, element: WORK_ORDER_ELEMENTS.WO_LIST_PAGE },
  { path: WORK_ORDER_ROUTES.ACCOUNT_WO_CREATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },
  { path: WORK_ORDER_ROUTES.ACCOUNT_WO_VIEW, element: WORK_ORDER_ELEMENTS.WO_DETAIL_PAGE },
  { path: WORK_ORDER_ROUTES.ACCOUNT_WO_UPDATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },

  // WO Under SR Standalone
  { path: WORK_ORDER_ROUTES.SR_WO_CREATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },
  { path: WORK_ORDER_ROUTES.SR_WO_VIEW, element: WORK_ORDER_ELEMENTS.WO_DETAIL_PAGE },
  { path: WORK_ORDER_ROUTES.SR_WO_UPDATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },

  // WO Under SR Under Account
  { path: WORK_ORDER_ROUTES.ACCOUNT_SR_WO_CREATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },
  { path: WORK_ORDER_ROUTES.ACCOUNT_SR_WO_VIEW, element: WORK_ORDER_ELEMENTS.WO_DETAIL_PAGE },
  { path: WORK_ORDER_ROUTES.ACCOUNT_SR_WO_UPDATE, element: WORK_ORDER_ELEMENTS.WO_CREATE_PAGE },
];

export { WORK_ORDER_ROUTES, WORK_ORDER_ELEMENTS };
